'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace SCStartUpSvcRef
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="FIleSupportDTO", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class FIleSupportDTO
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FILESUPPORT_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FILESUPPORT_NAMEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private VERSIONField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FILESUPPORT_ID() As String
            Get
                Return Me.FILESUPPORT_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FILESUPPORT_IDField, value) <> true) Then
                    Me.FILESUPPORT_IDField = value
                    Me.RaisePropertyChanged("FILESUPPORT_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FILESUPPORT_NAME() As String
            Get
                Return Me.FILESUPPORT_NAMEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FILESUPPORT_NAMEField, value) <> true) Then
                    Me.FILESUPPORT_NAMEField = value
                    Me.RaisePropertyChanged("FILESUPPORT_NAME")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property VERSION() As String
            Get
                Return Me.VERSIONField
            End Get
            Set
                If (Object.ReferenceEquals(Me.VERSIONField, value) <> true) Then
                    Me.VERSIONField = value
                    Me.RaisePropertyChanged("VERSION")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="SCStartUpSvcRef.ISCStartUpSvc")>  _
    Public Interface ISCStartUpSvc
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISCStartUpSvc/GetListFileSupportVersion", ReplyAction:="http://tempuri.org/ISCStartUpSvc/GetListFileSupportVersionResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SC_Common.SC_ServiceExceptions), Action:="http://tempuri.org/ISCStartUpSvc/GetListFileSupportVersionSC_ServiceExceptionsFau"& _ 
            "lt", Name:="SC_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_Common")>  _
        Function GetListFileSupportVersion() As System.Collections.Generic.List(Of SCStartUpSvcRef.FIleSupportDTO)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISCStartUpSvc/GetListFileSupportVersion", ReplyAction:="http://tempuri.org/ISCStartUpSvc/GetListFileSupportVersionResponse")>  _
        Function GetListFileSupportVersionAsync() As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of SCStartUpSvcRef.FIleSupportDTO))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISCStartUpSvc/UpdateFile", ReplyAction:="http://tempuri.org/ISCStartUpSvc/UpdateFileResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SC_Common.SC_ServiceExceptions), Action:="http://tempuri.org/ISCStartUpSvc/UpdateFileSC_ServiceExceptionsFault", Name:="SC_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_Common")>  _
        Function UpdateFile(ByVal pcFileSupportId As String, ByVal pcFileSupportName As String) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISCStartUpSvc/UpdateFile", ReplyAction:="http://tempuri.org/ISCStartUpSvc/UpdateFileResponse")>  _
        Function UpdateFileAsync(ByVal pcFileSupportId As String, ByVal pcFileSupportName As String) As System.Threading.Tasks.Task(Of Byte())
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ISCStartUpSvcChannel
        Inherits SCStartUpSvcRef.ISCStartUpSvc, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SCStartUpSvcClient
        Inherits System.ServiceModel.ClientBase(Of SCStartUpSvcRef.ISCStartUpSvc)
        Implements SCStartUpSvcRef.ISCStartUpSvc
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetListFileSupportVersion() As System.Collections.Generic.List(Of SCStartUpSvcRef.FIleSupportDTO) Implements SCStartUpSvcRef.ISCStartUpSvc.GetListFileSupportVersion
            Return MyBase.Channel.GetListFileSupportVersion
        End Function
        
        Public Function GetListFileSupportVersionAsync() As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of SCStartUpSvcRef.FIleSupportDTO)) Implements SCStartUpSvcRef.ISCStartUpSvc.GetListFileSupportVersionAsync
            Return MyBase.Channel.GetListFileSupportVersionAsync
        End Function
        
        Public Function UpdateFile(ByVal pcFileSupportId As String, ByVal pcFileSupportName As String) As Byte() Implements SCStartUpSvcRef.ISCStartUpSvc.UpdateFile
            Return MyBase.Channel.UpdateFile(pcFileSupportId, pcFileSupportName)
        End Function
        
        Public Function UpdateFileAsync(ByVal pcFileSupportId As String, ByVal pcFileSupportName As String) As System.Threading.Tasks.Task(Of Byte()) Implements SCStartUpSvcRef.ISCStartUpSvc.UpdateFileAsync
            Return MyBase.Channel.UpdateFileAsync(pcFileSupportId, pcFileSupportName)
        End Function
    End Class
End Namespace
