'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace CAB0100SvcRef
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LKM_CompanyOfficeDTO", [Namespace]:="http://schemas.datacontract.org/2004/07/CAB0100Back"),  _
     System.SerializableAttribute()>  _
    Partial Public Class LKM_CompanyOfficeDTO
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private COMPANY_OFFICEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private COMPANY_OFFICE_IDField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property COMPANY_OFFICE() As String
            Get
                Return Me.COMPANY_OFFICEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.COMPANY_OFFICEField, value) <> true) Then
                    Me.COMPANY_OFFICEField = value
                    Me.RaisePropertyChanged("COMPANY_OFFICE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property COMPANY_OFFICE_ID() As String
            Get
                Return Me.COMPANY_OFFICE_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.COMPANY_OFFICE_IDField, value) <> true) Then
                    Me.COMPANY_OFFICE_IDField = value
                    Me.RaisePropertyChanged("COMPANY_OFFICE_ID")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LKM_ParamDTO", [Namespace]:="http://schemas.datacontract.org/2004/07/CAB0100Back"),  _
     System.SerializableAttribute()>  _
    Partial Public Class LKM_ParamDTO
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PARAMETER_VALUEField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PARAMETER_VALUE() As String
            Get
                Return Me.PARAMETER_VALUEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PARAMETER_VALUEField, value) <> true) Then
                    Me.PARAMETER_VALUEField = value
                    Me.RaisePropertyChanged("PARAMETER_VALUE")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="CAB0100SvcRef.ICAB0100Svc")>  _
    Public Interface ICAB0100Svc
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICAB0100Svc/getCompany", ReplyAction:="http://tempuri.org/ICAB0100Svc/getCompanyResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SC_Common.SC_ServiceExceptions), Action:="http://tempuri.org/ICAB0100Svc/getCompanySC_ServiceExceptionsFault", Name:="SC_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_Common"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SC_Common.SC_ServiceExceptions)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of SC_Common.SC_Error))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SC_Common.SC_Error)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of SC_Common.SC_ErrorDetail))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SC_Common.SC_ErrorDetail)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of CAB0100SvcRef.LKM_CompanyOfficeDTO))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(CAB0100SvcRef.LKM_CompanyOfficeDTO)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of CAB0100SvcRef.LKM_ParamDTO))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(CAB0100SvcRef.LKM_ParamDTO)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Object)))>  _
        Function getCompany(ByVal poparam As System.Collections.Generic.List(Of Object)) As System.Collections.Generic.List(Of CAB0100SvcRef.LKM_CompanyOfficeDTO)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICAB0100Svc/getCompany", ReplyAction:="http://tempuri.org/ICAB0100Svc/getCompanyResponse")>  _
        Function getCompanyAsync(ByVal poparam As System.Collections.Generic.List(Of Object)) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of CAB0100SvcRef.LKM_CompanyOfficeDTO))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICAB0100Svc/Import", ReplyAction:="http://tempuri.org/ICAB0100Svc/ImportResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SC_Common.SC_ServiceExceptions), Action:="http://tempuri.org/ICAB0100Svc/ImportSC_ServiceExceptionsFault", Name:="SC_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_Common")>  _
        Sub Import(ByVal DataTable As System.Data.DataSet, ByVal company_office As String, ByVal user As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICAB0100Svc/Import", ReplyAction:="http://tempuri.org/ICAB0100Svc/ImportResponse")>  _
        Function ImportAsync(ByVal DataTable As System.Data.DataSet, ByVal company_office As String, ByVal user As String) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICAB0100Svc/getParamDoc", ReplyAction:="http://tempuri.org/ICAB0100Svc/getParamDocResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SC_Common.SC_ServiceExceptions), Action:="http://tempuri.org/ICAB0100Svc/getParamDocSC_ServiceExceptionsFault", Name:="SC_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_Common")>  _
        Function getParamDoc(ByVal param As String) As System.Collections.Generic.List(Of CAB0100SvcRef.LKM_ParamDTO)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICAB0100Svc/getParamDoc", ReplyAction:="http://tempuri.org/ICAB0100Svc/getParamDocResponse")>  _
        Function getParamDocAsync(ByVal param As String) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of CAB0100SvcRef.LKM_ParamDTO))
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ICAB0100SvcChannel
        Inherits CAB0100SvcRef.ICAB0100Svc, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CAB0100SvcClient
        Inherits System.ServiceModel.ClientBase(Of CAB0100SvcRef.ICAB0100Svc)
        Implements CAB0100SvcRef.ICAB0100Svc
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function getCompany(ByVal poparam As System.Collections.Generic.List(Of Object)) As System.Collections.Generic.List(Of CAB0100SvcRef.LKM_CompanyOfficeDTO) Implements CAB0100SvcRef.ICAB0100Svc.getCompany
            Return MyBase.Channel.getCompany(poparam)
        End Function
        
        Public Function getCompanyAsync(ByVal poparam As System.Collections.Generic.List(Of Object)) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of CAB0100SvcRef.LKM_CompanyOfficeDTO)) Implements CAB0100SvcRef.ICAB0100Svc.getCompanyAsync
            Return MyBase.Channel.getCompanyAsync(poparam)
        End Function
        
        Public Sub Import(ByVal DataTable As System.Data.DataSet, ByVal company_office As String, ByVal user As String) Implements CAB0100SvcRef.ICAB0100Svc.Import
            MyBase.Channel.Import(DataTable, company_office, user)
        End Sub
        
        Public Function ImportAsync(ByVal DataTable As System.Data.DataSet, ByVal company_office As String, ByVal user As String) As System.Threading.Tasks.Task Implements CAB0100SvcRef.ICAB0100Svc.ImportAsync
            Return MyBase.Channel.ImportAsync(DataTable, company_office, user)
        End Function
        
        Public Function getParamDoc(ByVal param As String) As System.Collections.Generic.List(Of CAB0100SvcRef.LKM_ParamDTO) Implements CAB0100SvcRef.ICAB0100Svc.getParamDoc
            Return MyBase.Channel.getParamDoc(param)
        End Function
        
        Public Function getParamDocAsync(ByVal param As String) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of CAB0100SvcRef.LKM_ParamDTO)) Implements CAB0100SvcRef.ICAB0100Svc.getParamDocAsync
            Return MyBase.Channel.getParamDocAsync(param)
        End Function
    End Class
End Namespace
