'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace SCMenuSvcRef
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="sys_appDTO", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class sys_appDTO
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private APP_DESCField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private APP_GROUP_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private APP_GROUP_NAMEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private APP_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private APP_NAMEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MODULE_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MODULE_NAMEField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property APP_DESC() As String
            Get
                Return Me.APP_DESCField
            End Get
            Set
                If (Object.ReferenceEquals(Me.APP_DESCField, value) <> true) Then
                    Me.APP_DESCField = value
                    Me.RaisePropertyChanged("APP_DESC")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property APP_GROUP_ID() As String
            Get
                Return Me.APP_GROUP_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.APP_GROUP_IDField, value) <> true) Then
                    Me.APP_GROUP_IDField = value
                    Me.RaisePropertyChanged("APP_GROUP_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property APP_GROUP_NAME() As String
            Get
                Return Me.APP_GROUP_NAMEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.APP_GROUP_NAMEField, value) <> true) Then
                    Me.APP_GROUP_NAMEField = value
                    Me.RaisePropertyChanged("APP_GROUP_NAME")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property APP_ID() As String
            Get
                Return Me.APP_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.APP_IDField, value) <> true) Then
                    Me.APP_IDField = value
                    Me.RaisePropertyChanged("APP_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property APP_NAME() As String
            Get
                Return Me.APP_NAMEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.APP_NAMEField, value) <> true) Then
                    Me.APP_NAMEField = value
                    Me.RaisePropertyChanged("APP_NAME")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MODULE_ID() As String
            Get
                Return Me.MODULE_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MODULE_IDField, value) <> true) Then
                    Me.MODULE_IDField = value
                    Me.RaisePropertyChanged("MODULE_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MODULE_NAME() As String
            Get
                Return Me.MODULE_NAMEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MODULE_NAMEField, value) <> true) Then
                    Me.MODULE_NAMEField = value
                    Me.RaisePropertyChanged("MODULE_NAME")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="loginDTO", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class loginDTO
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private COMPANY_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private COMPANY_NAMEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private COMPANY_OFFICE_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private COMPANY_OFFICE_MAP_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private COMPANY_OFFICE_NAMEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private USER_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private USER_NAMEField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property COMPANY_ID() As String
            Get
                Return Me.COMPANY_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.COMPANY_IDField, value) <> true) Then
                    Me.COMPANY_IDField = value
                    Me.RaisePropertyChanged("COMPANY_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property COMPANY_NAME() As String
            Get
                Return Me.COMPANY_NAMEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.COMPANY_NAMEField, value) <> true) Then
                    Me.COMPANY_NAMEField = value
                    Me.RaisePropertyChanged("COMPANY_NAME")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property COMPANY_OFFICE_ID() As String
            Get
                Return Me.COMPANY_OFFICE_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.COMPANY_OFFICE_IDField, value) <> true) Then
                    Me.COMPANY_OFFICE_IDField = value
                    Me.RaisePropertyChanged("COMPANY_OFFICE_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property COMPANY_OFFICE_MAP_ID() As String
            Get
                Return Me.COMPANY_OFFICE_MAP_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.COMPANY_OFFICE_MAP_IDField, value) <> true) Then
                    Me.COMPANY_OFFICE_MAP_IDField = value
                    Me.RaisePropertyChanged("COMPANY_OFFICE_MAP_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property COMPANY_OFFICE_NAME() As String
            Get
                Return Me.COMPANY_OFFICE_NAMEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.COMPANY_OFFICE_NAMEField, value) <> true) Then
                    Me.COMPANY_OFFICE_NAMEField = value
                    Me.RaisePropertyChanged("COMPANY_OFFICE_NAME")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property USER_ID() As String
            Get
                Return Me.USER_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.USER_IDField, value) <> true) Then
                    Me.USER_IDField = value
                    Me.RaisePropertyChanged("USER_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property USER_NAME() As String
            Get
                Return Me.USER_NAMEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.USER_NAMEField, value) <> true) Then
                    Me.USER_NAMEField = value
                    Me.RaisePropertyChanged("USER_NAME")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RoleAppDTO", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class RoleAppDTO
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Add_PermitField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private App_IdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Delete_PermitField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Edit_PermitField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Read_PermitField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Add_Permit() As Boolean
            Get
                Return Me.Add_PermitField
            End Get
            Set
                If (Me.Add_PermitField.Equals(value) <> true) Then
                    Me.Add_PermitField = value
                    Me.RaisePropertyChanged("Add_Permit")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property App_Id() As String
            Get
                Return Me.App_IdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.App_IdField, value) <> true) Then
                    Me.App_IdField = value
                    Me.RaisePropertyChanged("App_Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Delete_Permit() As Boolean
            Get
                Return Me.Delete_PermitField
            End Get
            Set
                If (Me.Delete_PermitField.Equals(value) <> true) Then
                    Me.Delete_PermitField = value
                    Me.RaisePropertyChanged("Delete_Permit")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Edit_Permit() As Boolean
            Get
                Return Me.Edit_PermitField
            End Get
            Set
                If (Me.Edit_PermitField.Equals(value) <> true) Then
                    Me.Edit_PermitField = value
                    Me.RaisePropertyChanged("Edit_Permit")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Read_Permit() As Boolean
            Get
                Return Me.Read_PermitField
            End Get
            Set
                If (Me.Read_PermitField.Equals(value) <> true) Then
                    Me.Read_PermitField = value
                    Me.RaisePropertyChanged("Read_Permit")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="SCMenuSvcRef.ISCMenuSvc")>  _
    Public Interface ISCMenuSvc
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISCMenuSvc/GetListApp", ReplyAction:="http://tempuri.org/ISCMenuSvc/GetListAppResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SC_Common.SC_ServiceExceptions), Action:="http://tempuri.org/ISCMenuSvc/GetListAppSC_ServiceExceptionsFault", Name:="SC_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_Common")>  _
        Function GetListApp(ByVal pcUserId As String) As System.Collections.Generic.List(Of SCMenuSvcRef.sys_appDTO)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISCMenuSvc/GetListApp", ReplyAction:="http://tempuri.org/ISCMenuSvc/GetListAppResponse")>  _
        Function GetListAppAsync(ByVal pcUserId As String) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of SCMenuSvcRef.sys_appDTO))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISCMenuSvc/Login", ReplyAction:="http://tempuri.org/ISCMenuSvc/LoginResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SC_Common.SC_ServiceExceptions), Action:="http://tempuri.org/ISCMenuSvc/LoginSC_ServiceExceptionsFault", Name:="SC_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_Common")>  _
        Function Login(ByVal pcUserId As String, ByVal pcPassword As String) As SCMenuSvcRef.loginDTO
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISCMenuSvc/Login", ReplyAction:="http://tempuri.org/ISCMenuSvc/LoginResponse")>  _
        Function LoginAsync(ByVal pcUserId As String, ByVal pcPassword As String) As System.Threading.Tasks.Task(Of SCMenuSvcRef.loginDTO)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISCMenuSvc/GetRoleApp", ReplyAction:="http://tempuri.org/ISCMenuSvc/GetRoleAppResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SC_Common.SC_ServiceExceptions), Action:="http://tempuri.org/ISCMenuSvc/GetRoleAppSC_ServiceExceptionsFault", Name:="SC_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_Common")>  _
        Function GetRoleApp(ByVal pcUserId As String) As System.Collections.Generic.List(Of SCMenuSvcRef.RoleAppDTO)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISCMenuSvc/GetRoleApp", ReplyAction:="http://tempuri.org/ISCMenuSvc/GetRoleAppResponse")>  _
        Function GetRoleAppAsync(ByVal pcUserId As String) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of SCMenuSvcRef.RoleAppDTO))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISCMenuSvc/ChangePassword", ReplyAction:="http://tempuri.org/ISCMenuSvc/ChangePasswordResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SC_Common.SC_ServiceExceptions), Action:="http://tempuri.org/ISCMenuSvc/ChangePasswordSC_ServiceExceptionsFault", Name:="SC_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_Common")>  _
        Sub ChangePassword(ByVal pcUserId As String, ByVal pcOldPassword As String, ByVal pcNewPassword As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISCMenuSvc/ChangePassword", ReplyAction:="http://tempuri.org/ISCMenuSvc/ChangePasswordResponse")>  _
        Function ChangePasswordAsync(ByVal pcUserId As String, ByVal pcOldPassword As String, ByVal pcNewPassword As String) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISCMenuSvc/UpdateAppDll", ReplyAction:="http://tempuri.org/ISCMenuSvc/UpdateAppDllResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SC_Common.SC_ServiceExceptions), Action:="http://tempuri.org/ISCMenuSvc/UpdateAppDllSC_ServiceExceptionsFault", Name:="SC_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_Common")>  _
        Function UpdateAppDll(ByVal pcAppId As String) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISCMenuSvc/UpdateAppDll", ReplyAction:="http://tempuri.org/ISCMenuSvc/UpdateAppDllResponse")>  _
        Function UpdateAppDllAsync(ByVal pcAppId As String) As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISCMenuSvc/AppDllLatestVersion", ReplyAction:="http://tempuri.org/ISCMenuSvc/AppDllLatestVersionResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SC_Common.SC_ServiceExceptions), Action:="http://tempuri.org/ISCMenuSvc/AppDllLatestVersionSC_ServiceExceptionsFault", Name:="SC_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_Common")>  _
        Function AppDllLatestVersion(ByVal pcAppId As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISCMenuSvc/AppDllLatestVersion", ReplyAction:="http://tempuri.org/ISCMenuSvc/AppDllLatestVersionResponse")>  _
        Function AppDllLatestVersionAsync(ByVal pcAppId As String) As System.Threading.Tasks.Task(Of String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ISCMenuSvcChannel
        Inherits SCMenuSvcRef.ISCMenuSvc, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SCMenuSvcClient
        Inherits System.ServiceModel.ClientBase(Of SCMenuSvcRef.ISCMenuSvc)
        Implements SCMenuSvcRef.ISCMenuSvc
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetListApp(ByVal pcUserId As String) As System.Collections.Generic.List(Of SCMenuSvcRef.sys_appDTO) Implements SCMenuSvcRef.ISCMenuSvc.GetListApp
            Return MyBase.Channel.GetListApp(pcUserId)
        End Function
        
        Public Function GetListAppAsync(ByVal pcUserId As String) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of SCMenuSvcRef.sys_appDTO)) Implements SCMenuSvcRef.ISCMenuSvc.GetListAppAsync
            Return MyBase.Channel.GetListAppAsync(pcUserId)
        End Function
        
        Public Function Login(ByVal pcUserId As String, ByVal pcPassword As String) As SCMenuSvcRef.loginDTO Implements SCMenuSvcRef.ISCMenuSvc.Login
            Return MyBase.Channel.Login(pcUserId, pcPassword)
        End Function
        
        Public Function LoginAsync(ByVal pcUserId As String, ByVal pcPassword As String) As System.Threading.Tasks.Task(Of SCMenuSvcRef.loginDTO) Implements SCMenuSvcRef.ISCMenuSvc.LoginAsync
            Return MyBase.Channel.LoginAsync(pcUserId, pcPassword)
        End Function
        
        Public Function GetRoleApp(ByVal pcUserId As String) As System.Collections.Generic.List(Of SCMenuSvcRef.RoleAppDTO) Implements SCMenuSvcRef.ISCMenuSvc.GetRoleApp
            Return MyBase.Channel.GetRoleApp(pcUserId)
        End Function
        
        Public Function GetRoleAppAsync(ByVal pcUserId As String) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of SCMenuSvcRef.RoleAppDTO)) Implements SCMenuSvcRef.ISCMenuSvc.GetRoleAppAsync
            Return MyBase.Channel.GetRoleAppAsync(pcUserId)
        End Function
        
        Public Sub ChangePassword(ByVal pcUserId As String, ByVal pcOldPassword As String, ByVal pcNewPassword As String) Implements SCMenuSvcRef.ISCMenuSvc.ChangePassword
            MyBase.Channel.ChangePassword(pcUserId, pcOldPassword, pcNewPassword)
        End Sub
        
        Public Function ChangePasswordAsync(ByVal pcUserId As String, ByVal pcOldPassword As String, ByVal pcNewPassword As String) As System.Threading.Tasks.Task Implements SCMenuSvcRef.ISCMenuSvc.ChangePasswordAsync
            Return MyBase.Channel.ChangePasswordAsync(pcUserId, pcOldPassword, pcNewPassword)
        End Function
        
        Public Function UpdateAppDll(ByVal pcAppId As String) As Byte() Implements SCMenuSvcRef.ISCMenuSvc.UpdateAppDll
            Return MyBase.Channel.UpdateAppDll(pcAppId)
        End Function
        
        Public Function UpdateAppDllAsync(ByVal pcAppId As String) As System.Threading.Tasks.Task(Of Byte()) Implements SCMenuSvcRef.ISCMenuSvc.UpdateAppDllAsync
            Return MyBase.Channel.UpdateAppDllAsync(pcAppId)
        End Function
        
        Public Function AppDllLatestVersion(ByVal pcAppId As String) As String Implements SCMenuSvcRef.ISCMenuSvc.AppDllLatestVersion
            Return MyBase.Channel.AppDllLatestVersion(pcAppId)
        End Function
        
        Public Function AppDllLatestVersionAsync(ByVal pcAppId As String) As System.Threading.Tasks.Task(Of String) Implements SCMenuSvcRef.ISCMenuSvc.AppDllLatestVersionAsync
            Return MyBase.Channel.AppDllLatestVersionAsync(pcAppId)
        End Function
    End Class
End Namespace
