'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace RPR0200SvcRef
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SC_DTOBase", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_BackEnd"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(RPR0200SvcRef.RPR0200DTO01))>  _
    Partial Public Class SC_DTOBase
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RPR0200DTO01", [Namespace]:="http://schemas.datacontract.org/2004/07/RPR0200Back"),  _
     System.SerializableAttribute()>  _
    Partial Public Class RPR0200DTO01
        Inherits RPR0200SvcRef.SC_DTOBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BARCODEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private COMPANY_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private COMPANY_OFFICE_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CREA_BYField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CREA_DATEField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FROM_DATEField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OUTLET_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OUTLET_NAMEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private REPAIR_DETAILField As System.Collections.Generic.List(Of RPR0200SvcRef.Repair_DetailDTO)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private REPAIR_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TO_DATEField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UPD_BYField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UPD_DATEField As Date
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BARCODE() As String
            Get
                Return Me.BARCODEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BARCODEField, value) <> true) Then
                    Me.BARCODEField = value
                    Me.RaisePropertyChanged("BARCODE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property COMPANY_ID() As String
            Get
                Return Me.COMPANY_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.COMPANY_IDField, value) <> true) Then
                    Me.COMPANY_IDField = value
                    Me.RaisePropertyChanged("COMPANY_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property COMPANY_OFFICE_ID() As String
            Get
                Return Me.COMPANY_OFFICE_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.COMPANY_OFFICE_IDField, value) <> true) Then
                    Me.COMPANY_OFFICE_IDField = value
                    Me.RaisePropertyChanged("COMPANY_OFFICE_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CREA_BY() As String
            Get
                Return Me.CREA_BYField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CREA_BYField, value) <> true) Then
                    Me.CREA_BYField = value
                    Me.RaisePropertyChanged("CREA_BY")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CREA_DATE() As Date
            Get
                Return Me.CREA_DATEField
            End Get
            Set
                If (Me.CREA_DATEField.Equals(value) <> true) Then
                    Me.CREA_DATEField = value
                    Me.RaisePropertyChanged("CREA_DATE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FROM_DATE() As Date
            Get
                Return Me.FROM_DATEField
            End Get
            Set
                If (Me.FROM_DATEField.Equals(value) <> true) Then
                    Me.FROM_DATEField = value
                    Me.RaisePropertyChanged("FROM_DATE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OUTLET_ID() As String
            Get
                Return Me.OUTLET_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OUTLET_IDField, value) <> true) Then
                    Me.OUTLET_IDField = value
                    Me.RaisePropertyChanged("OUTLET_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OUTLET_NAME() As String
            Get
                Return Me.OUTLET_NAMEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OUTLET_NAMEField, value) <> true) Then
                    Me.OUTLET_NAMEField = value
                    Me.RaisePropertyChanged("OUTLET_NAME")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property REPAIR_DETAIL() As System.Collections.Generic.List(Of RPR0200SvcRef.Repair_DetailDTO)
            Get
                Return Me.REPAIR_DETAILField
            End Get
            Set
                If (Object.ReferenceEquals(Me.REPAIR_DETAILField, value) <> true) Then
                    Me.REPAIR_DETAILField = value
                    Me.RaisePropertyChanged("REPAIR_DETAIL")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property REPAIR_ID() As String
            Get
                Return Me.REPAIR_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.REPAIR_IDField, value) <> true) Then
                    Me.REPAIR_IDField = value
                    Me.RaisePropertyChanged("REPAIR_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TO_DATE() As Date
            Get
                Return Me.TO_DATEField
            End Get
            Set
                If (Me.TO_DATEField.Equals(value) <> true) Then
                    Me.TO_DATEField = value
                    Me.RaisePropertyChanged("TO_DATE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UPD_BY() As String
            Get
                Return Me.UPD_BYField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UPD_BYField, value) <> true) Then
                    Me.UPD_BYField = value
                    Me.RaisePropertyChanged("UPD_BY")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UPD_DATE() As Date
            Get
                Return Me.UPD_DATEField
            End Get
            Set
                If (Me.UPD_DATEField.Equals(value) <> true) Then
                    Me.UPD_DATEField = value
                    Me.RaisePropertyChanged("UPD_DATE")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Repair_DetailDTO", [Namespace]:="http://schemas.datacontract.org/2004/07/RPR0200Back"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(RPR0200SvcRef.SC_DTOBase)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(RPR0200SvcRef.eCRUDMode)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(SC_Common.SC_ServiceExceptions)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(System.Collections.Generic.List(Of SC_Common.SC_Error))),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(SC_Common.SC_Error)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(System.Collections.Generic.List(Of SC_Common.SC_ErrorDetail))),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(SC_Common.SC_ErrorDetail)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(System.Collections.Generic.List(Of Object))),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(RPR0200SvcRef.RPR0200DTO01)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(System.Collections.Generic.List(Of RPR0200SvcRef.Repair_DetailDTO))),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(System.Collections.Generic.List(Of RPR0200SvcRef.RPR0200DTO02))),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(RPR0200SvcRef.RPR0200DTO02)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(System.Collections.Generic.List(Of RPR0200SvcRef.LKM_CompanyDTO))),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(RPR0200SvcRef.LKM_CompanyDTO)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(System.Collections.Generic.List(Of RPR0200SvcRef.LKM_CompanyOfficeDTO))),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(RPR0200SvcRef.LKM_CompanyOfficeDTO)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(System.Collections.Generic.List(Of RPR0200SvcRef.LKM_OutletDTO))),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(RPR0200SvcRef.LKM_OutletDTO)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(System.Collections.Generic.List(Of RPR0200SvcRef.LKM_SparepartDTO))),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(RPR0200SvcRef.LKM_SparepartDTO))>  _
    Partial Public Class Repair_DetailDTO
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CREA_BYField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CREA_DATEField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HARGA_PARTField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private KD_PARTField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NAMA_PARTField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private QTY_PARTField As Object
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private REPAIR_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SATUAN_PARTField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UPD_BYField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UPD_DATEField As Date
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CREA_BY() As String
            Get
                Return Me.CREA_BYField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CREA_BYField, value) <> true) Then
                    Me.CREA_BYField = value
                    Me.RaisePropertyChanged("CREA_BY")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CREA_DATE() As Date
            Get
                Return Me.CREA_DATEField
            End Get
            Set
                If (Me.CREA_DATEField.Equals(value) <> true) Then
                    Me.CREA_DATEField = value
                    Me.RaisePropertyChanged("CREA_DATE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property HARGA_PART() As Decimal
            Get
                Return Me.HARGA_PARTField
            End Get
            Set
                If (Me.HARGA_PARTField.Equals(value) <> true) Then
                    Me.HARGA_PARTField = value
                    Me.RaisePropertyChanged("HARGA_PART")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property KD_PART() As Integer
            Get
                Return Me.KD_PARTField
            End Get
            Set
                If (Me.KD_PARTField.Equals(value) <> true) Then
                    Me.KD_PARTField = value
                    Me.RaisePropertyChanged("KD_PART")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NAMA_PART() As String
            Get
                Return Me.NAMA_PARTField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NAMA_PARTField, value) <> true) Then
                    Me.NAMA_PARTField = value
                    Me.RaisePropertyChanged("NAMA_PART")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property QTY_PART() As Object
            Get
                Return Me.QTY_PARTField
            End Get
            Set
                If (Object.ReferenceEquals(Me.QTY_PARTField, value) <> true) Then
                    Me.QTY_PARTField = value
                    Me.RaisePropertyChanged("QTY_PART")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property REPAIR_ID() As String
            Get
                Return Me.REPAIR_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.REPAIR_IDField, value) <> true) Then
                    Me.REPAIR_IDField = value
                    Me.RaisePropertyChanged("REPAIR_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SATUAN_PART() As String
            Get
                Return Me.SATUAN_PARTField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SATUAN_PARTField, value) <> true) Then
                    Me.SATUAN_PARTField = value
                    Me.RaisePropertyChanged("SATUAN_PART")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UPD_BY() As String
            Get
                Return Me.UPD_BYField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UPD_BYField, value) <> true) Then
                    Me.UPD_BYField = value
                    Me.RaisePropertyChanged("UPD_BY")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UPD_DATE() As Date
            Get
                Return Me.UPD_DATEField
            End Get
            Set
                If (Me.UPD_DATEField.Equals(value) <> true) Then
                    Me.UPD_DATEField = value
                    Me.RaisePropertyChanged("UPD_DATE")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="eCRUDMode", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_BackEnd")>  _
    Public Enum eCRUDMode As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        NormalMode = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        AddMode = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        EditMode = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        DeleteMode = 3
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RPR0200DTO02", [Namespace]:="http://schemas.datacontract.org/2004/07/RPR0200Back"),  _
     System.SerializableAttribute()>  _
    Partial Public Class RPR0200DTO02
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BARCODEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private COMPANY_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private COMPANY_OFFICE_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CREA_BYField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CREA_DATEField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FROM_DATEField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OUTLET_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OUTLET_NAMEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private REPAIR_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TO_DATEField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UPD_BYField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UPD_DATEField As Date
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BARCODE() As String
            Get
                Return Me.BARCODEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BARCODEField, value) <> true) Then
                    Me.BARCODEField = value
                    Me.RaisePropertyChanged("BARCODE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property COMPANY_ID() As String
            Get
                Return Me.COMPANY_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.COMPANY_IDField, value) <> true) Then
                    Me.COMPANY_IDField = value
                    Me.RaisePropertyChanged("COMPANY_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property COMPANY_OFFICE_ID() As String
            Get
                Return Me.COMPANY_OFFICE_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.COMPANY_OFFICE_IDField, value) <> true) Then
                    Me.COMPANY_OFFICE_IDField = value
                    Me.RaisePropertyChanged("COMPANY_OFFICE_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CREA_BY() As String
            Get
                Return Me.CREA_BYField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CREA_BYField, value) <> true) Then
                    Me.CREA_BYField = value
                    Me.RaisePropertyChanged("CREA_BY")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CREA_DATE() As Date
            Get
                Return Me.CREA_DATEField
            End Get
            Set
                If (Me.CREA_DATEField.Equals(value) <> true) Then
                    Me.CREA_DATEField = value
                    Me.RaisePropertyChanged("CREA_DATE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FROM_DATE() As Date
            Get
                Return Me.FROM_DATEField
            End Get
            Set
                If (Me.FROM_DATEField.Equals(value) <> true) Then
                    Me.FROM_DATEField = value
                    Me.RaisePropertyChanged("FROM_DATE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OUTLET_ID() As String
            Get
                Return Me.OUTLET_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OUTLET_IDField, value) <> true) Then
                    Me.OUTLET_IDField = value
                    Me.RaisePropertyChanged("OUTLET_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OUTLET_NAME() As String
            Get
                Return Me.OUTLET_NAMEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OUTLET_NAMEField, value) <> true) Then
                    Me.OUTLET_NAMEField = value
                    Me.RaisePropertyChanged("OUTLET_NAME")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property REPAIR_ID() As String
            Get
                Return Me.REPAIR_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.REPAIR_IDField, value) <> true) Then
                    Me.REPAIR_IDField = value
                    Me.RaisePropertyChanged("REPAIR_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TO_DATE() As Date
            Get
                Return Me.TO_DATEField
            End Get
            Set
                If (Me.TO_DATEField.Equals(value) <> true) Then
                    Me.TO_DATEField = value
                    Me.RaisePropertyChanged("TO_DATE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UPD_BY() As String
            Get
                Return Me.UPD_BYField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UPD_BYField, value) <> true) Then
                    Me.UPD_BYField = value
                    Me.RaisePropertyChanged("UPD_BY")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UPD_DATE() As Date
            Get
                Return Me.UPD_DATEField
            End Get
            Set
                If (Me.UPD_DATEField.Equals(value) <> true) Then
                    Me.UPD_DATEField = value
                    Me.RaisePropertyChanged("UPD_DATE")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LKM_CompanyDTO", [Namespace]:="http://schemas.datacontract.org/2004/07/RPR0200Back"),  _
     System.SerializableAttribute()>  _
    Partial Public Class LKM_CompanyDTO
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private COMPANY_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private COMPANY_NAMEField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property COMPANY_ID() As String
            Get
                Return Me.COMPANY_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.COMPANY_IDField, value) <> true) Then
                    Me.COMPANY_IDField = value
                    Me.RaisePropertyChanged("COMPANY_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property COMPANY_NAME() As String
            Get
                Return Me.COMPANY_NAMEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.COMPANY_NAMEField, value) <> true) Then
                    Me.COMPANY_NAMEField = value
                    Me.RaisePropertyChanged("COMPANY_NAME")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LKM_CompanyOfficeDTO", [Namespace]:="http://schemas.datacontract.org/2004/07/RPR0200Back"),  _
     System.SerializableAttribute()>  _
    Partial Public Class LKM_CompanyOfficeDTO
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private COMPANY_OFFICEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private COMPANY_OFFICE_IDField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property COMPANY_OFFICE() As String
            Get
                Return Me.COMPANY_OFFICEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.COMPANY_OFFICEField, value) <> true) Then
                    Me.COMPANY_OFFICEField = value
                    Me.RaisePropertyChanged("COMPANY_OFFICE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property COMPANY_OFFICE_ID() As String
            Get
                Return Me.COMPANY_OFFICE_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.COMPANY_OFFICE_IDField, value) <> true) Then
                    Me.COMPANY_OFFICE_IDField = value
                    Me.RaisePropertyChanged("COMPANY_OFFICE_ID")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LKM_OutletDTO", [Namespace]:="http://schemas.datacontract.org/2004/07/RPR0200Back"),  _
     System.SerializableAttribute()>  _
    Partial Public Class LKM_OutletDTO
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OUTLET_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OUTLET_NAMEField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OUTLET_ID() As String
            Get
                Return Me.OUTLET_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OUTLET_IDField, value) <> true) Then
                    Me.OUTLET_IDField = value
                    Me.RaisePropertyChanged("OUTLET_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OUTLET_NAME() As String
            Get
                Return Me.OUTLET_NAMEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OUTLET_NAMEField, value) <> true) Then
                    Me.OUTLET_NAMEField = value
                    Me.RaisePropertyChanged("OUTLET_NAME")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LKM_SparepartDTO", [Namespace]:="http://schemas.datacontract.org/2004/07/RPR0200Back"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(RPR0200SvcRef.SC_DTOBase)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(RPR0200SvcRef.eCRUDMode)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(SC_Common.SC_ServiceExceptions)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(System.Collections.Generic.List(Of SC_Common.SC_Error))),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(SC_Common.SC_Error)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(System.Collections.Generic.List(Of SC_Common.SC_ErrorDetail))),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(SC_Common.SC_ErrorDetail)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(System.Collections.Generic.List(Of Object))),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(RPR0200SvcRef.RPR0200DTO01)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(System.Collections.Generic.List(Of RPR0200SvcRef.Repair_DetailDTO))),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(RPR0200SvcRef.Repair_DetailDTO)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(System.Collections.Generic.List(Of RPR0200SvcRef.RPR0200DTO02))),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(RPR0200SvcRef.RPR0200DTO02)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(System.Collections.Generic.List(Of RPR0200SvcRef.LKM_CompanyDTO))),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(RPR0200SvcRef.LKM_CompanyDTO)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(System.Collections.Generic.List(Of RPR0200SvcRef.LKM_CompanyOfficeDTO))),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(RPR0200SvcRef.LKM_CompanyOfficeDTO)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(System.Collections.Generic.List(Of RPR0200SvcRef.LKM_OutletDTO))),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(RPR0200SvcRef.LKM_OutletDTO)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(System.Collections.Generic.List(Of RPR0200SvcRef.LKM_SparepartDTO)))>  _
    Partial Public Class LKM_SparepartDTO
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private COMPANY_OFFICE_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HARGA_PARTField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private KD_PARTField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NAMA_PARTField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PILIHField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SATUAN_PARTField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private STOCK_PARTField As Object
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property COMPANY_OFFICE_ID() As String
            Get
                Return Me.COMPANY_OFFICE_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.COMPANY_OFFICE_IDField, value) <> true) Then
                    Me.COMPANY_OFFICE_IDField = value
                    Me.RaisePropertyChanged("COMPANY_OFFICE_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property HARGA_PART() As Decimal
            Get
                Return Me.HARGA_PARTField
            End Get
            Set
                If (Me.HARGA_PARTField.Equals(value) <> true) Then
                    Me.HARGA_PARTField = value
                    Me.RaisePropertyChanged("HARGA_PART")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property KD_PART() As Integer
            Get
                Return Me.KD_PARTField
            End Get
            Set
                If (Me.KD_PARTField.Equals(value) <> true) Then
                    Me.KD_PARTField = value
                    Me.RaisePropertyChanged("KD_PART")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NAMA_PART() As String
            Get
                Return Me.NAMA_PARTField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NAMA_PARTField, value) <> true) Then
                    Me.NAMA_PARTField = value
                    Me.RaisePropertyChanged("NAMA_PART")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PILIH() As Boolean
            Get
                Return Me.PILIHField
            End Get
            Set
                If (Me.PILIHField.Equals(value) <> true) Then
                    Me.PILIHField = value
                    Me.RaisePropertyChanged("PILIH")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SATUAN_PART() As String
            Get
                Return Me.SATUAN_PARTField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SATUAN_PARTField, value) <> true) Then
                    Me.SATUAN_PARTField = value
                    Me.RaisePropertyChanged("SATUAN_PART")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property STOCK_PART() As Object
            Get
                Return Me.STOCK_PARTField
            End Get
            Set
                If (Object.ReferenceEquals(Me.STOCK_PARTField, value) <> true) Then
                    Me.STOCK_PARTField = value
                    Me.RaisePropertyChanged("STOCK_PART")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="RPR0200SvcRef.IRPR0200Svc")>  _
    Public Interface IRPR0200Svc
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SC_IServicebaseOf_RPR0200DTO01/Svc_SC_GetRecord", ReplyAction:="http://tempuri.org/SC_IServicebaseOf_RPR0200DTO01/Svc_SC_GetRecordResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SC_Common.SC_ServiceExceptions), Action:="http://tempuri.org/SC_IServicebaseOf_RPR0200DTO01/Svc_SC_GetRecordSC_ServiceExcep"& _ 
            "tionsFault", Name:="SC_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_Common")>  _
        Function Svc_SC_GetRecord(ByVal poEntity As RPR0200SvcRef.RPR0200DTO01, ByVal poCRUDMode As RPR0200SvcRef.eCRUDMode) As RPR0200SvcRef.RPR0200DTO01
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SC_IServicebaseOf_RPR0200DTO01/Svc_SC_GetRecord", ReplyAction:="http://tempuri.org/SC_IServicebaseOf_RPR0200DTO01/Svc_SC_GetRecordResponse")>  _
        Function Svc_SC_GetRecordAsync(ByVal poEntity As RPR0200SvcRef.RPR0200DTO01, ByVal poCRUDMode As RPR0200SvcRef.eCRUDMode) As System.Threading.Tasks.Task(Of RPR0200SvcRef.RPR0200DTO01)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SC_IServicebaseOf_RPR0200DTO01/Svc_SC_Save", ReplyAction:="http://tempuri.org/SC_IServicebaseOf_RPR0200DTO01/Svc_SC_SaveResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SC_Common.SC_ServiceExceptions), Action:="http://tempuri.org/SC_IServicebaseOf_RPR0200DTO01/Svc_SC_SaveSC_ServiceExceptions"& _ 
            "Fault", Name:="SC_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_Common")>  _
        Function Svc_SC_Save(ByVal poEntity As RPR0200SvcRef.RPR0200DTO01, ByVal poCRUDMode As RPR0200SvcRef.eCRUDMode) As RPR0200SvcRef.RPR0200DTO01
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SC_IServicebaseOf_RPR0200DTO01/Svc_SC_Save", ReplyAction:="http://tempuri.org/SC_IServicebaseOf_RPR0200DTO01/Svc_SC_SaveResponse")>  _
        Function Svc_SC_SaveAsync(ByVal poEntity As RPR0200SvcRef.RPR0200DTO01, ByVal poCRUDMode As RPR0200SvcRef.eCRUDMode) As System.Threading.Tasks.Task(Of RPR0200SvcRef.RPR0200DTO01)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SC_IServicebaseOf_RPR0200DTO01/Svc_SC_Delete", ReplyAction:="http://tempuri.org/SC_IServicebaseOf_RPR0200DTO01/Svc_SC_DeleteResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SC_Common.SC_ServiceExceptions), Action:="http://tempuri.org/SC_IServicebaseOf_RPR0200DTO01/Svc_SC_DeleteSC_ServiceExceptio"& _ 
            "nsFault", Name:="SC_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_Common")>  _
        Sub Svc_SC_Delete(ByVal poEntity As RPR0200SvcRef.RPR0200DTO01)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SC_IServicebaseOf_RPR0200DTO01/Svc_SC_Delete", ReplyAction:="http://tempuri.org/SC_IServicebaseOf_RPR0200DTO01/Svc_SC_DeleteResponse")>  _
        Function Svc_SC_DeleteAsync(ByVal poEntity As RPR0200SvcRef.RPR0200DTO01) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IRPR0200Svc/getList", ReplyAction:="http://tempuri.org/IRPR0200Svc/getListResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SC_Common.SC_ServiceExceptions), Action:="http://tempuri.org/IRPR0200Svc/getListSC_ServiceExceptionsFault", Name:="SC_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_Common"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(RPR0200SvcRef.SC_DTOBase)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(RPR0200SvcRef.eCRUDMode)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SC_Common.SC_ServiceExceptions)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of SC_Common.SC_Error))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SC_Common.SC_Error)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of SC_Common.SC_ErrorDetail))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SC_Common.SC_ErrorDetail)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Object))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(RPR0200SvcRef.RPR0200DTO01)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of RPR0200SvcRef.Repair_DetailDTO))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(RPR0200SvcRef.Repair_DetailDTO)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of RPR0200SvcRef.RPR0200DTO02))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(RPR0200SvcRef.RPR0200DTO02)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of RPR0200SvcRef.LKM_CompanyDTO))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(RPR0200SvcRef.LKM_CompanyDTO)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of RPR0200SvcRef.LKM_CompanyOfficeDTO))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(RPR0200SvcRef.LKM_CompanyOfficeDTO)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of RPR0200SvcRef.LKM_OutletDTO))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(RPR0200SvcRef.LKM_OutletDTO)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of RPR0200SvcRef.LKM_SparepartDTO))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(RPR0200SvcRef.LKM_SparepartDTO))>  _
        Function getList(ByVal poparam As System.Collections.Generic.List(Of Object)) As System.Collections.Generic.List(Of RPR0200SvcRef.RPR0200DTO02)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IRPR0200Svc/getList", ReplyAction:="http://tempuri.org/IRPR0200Svc/getListResponse")>  _
        Function getListAsync(ByVal poparam As System.Collections.Generic.List(Of Object)) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of RPR0200SvcRef.RPR0200DTO02))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IRPR0200Svc/getList_Detail", ReplyAction:="http://tempuri.org/IRPR0200Svc/getList_DetailResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SC_Common.SC_ServiceExceptions), Action:="http://tempuri.org/IRPR0200Svc/getList_DetailSC_ServiceExceptionsFault", Name:="SC_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_Common")>  _
        Function getList_Detail(ByVal poparam As RPR0200SvcRef.RPR0200DTO01) As System.Collections.Generic.List(Of RPR0200SvcRef.Repair_DetailDTO)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IRPR0200Svc/getList_Detail", ReplyAction:="http://tempuri.org/IRPR0200Svc/getList_DetailResponse")>  _
        Function getList_DetailAsync(ByVal poparam As RPR0200SvcRef.RPR0200DTO01) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of RPR0200SvcRef.Repair_DetailDTO))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IRPR0200Svc/getCompany", ReplyAction:="http://tempuri.org/IRPR0200Svc/getCompanyResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SC_Common.SC_ServiceExceptions), Action:="http://tempuri.org/IRPR0200Svc/getCompanySC_ServiceExceptionsFault", Name:="SC_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_Common"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(RPR0200SvcRef.SC_DTOBase)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(RPR0200SvcRef.eCRUDMode)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SC_Common.SC_ServiceExceptions)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of SC_Common.SC_Error))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SC_Common.SC_Error)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of SC_Common.SC_ErrorDetail))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SC_Common.SC_ErrorDetail)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Object))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(RPR0200SvcRef.RPR0200DTO01)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of RPR0200SvcRef.Repair_DetailDTO))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(RPR0200SvcRef.Repair_DetailDTO)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of RPR0200SvcRef.RPR0200DTO02))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(RPR0200SvcRef.RPR0200DTO02)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of RPR0200SvcRef.LKM_CompanyDTO))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(RPR0200SvcRef.LKM_CompanyDTO)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of RPR0200SvcRef.LKM_CompanyOfficeDTO))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(RPR0200SvcRef.LKM_CompanyOfficeDTO)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of RPR0200SvcRef.LKM_OutletDTO))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(RPR0200SvcRef.LKM_OutletDTO)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of RPR0200SvcRef.LKM_SparepartDTO))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(RPR0200SvcRef.LKM_SparepartDTO))>  _
        Function getCompany(ByVal poparam As System.Collections.Generic.List(Of Object)) As System.Collections.Generic.List(Of RPR0200SvcRef.LKM_CompanyDTO)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IRPR0200Svc/getCompany", ReplyAction:="http://tempuri.org/IRPR0200Svc/getCompanyResponse")>  _
        Function getCompanyAsync(ByVal poparam As System.Collections.Generic.List(Of Object)) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of RPR0200SvcRef.LKM_CompanyDTO))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IRPR0200Svc/getOffice", ReplyAction:="http://tempuri.org/IRPR0200Svc/getOfficeResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SC_Common.SC_ServiceExceptions), Action:="http://tempuri.org/IRPR0200Svc/getOfficeSC_ServiceExceptionsFault", Name:="SC_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_Common"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(RPR0200SvcRef.SC_DTOBase)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(RPR0200SvcRef.eCRUDMode)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SC_Common.SC_ServiceExceptions)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of SC_Common.SC_Error))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SC_Common.SC_Error)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of SC_Common.SC_ErrorDetail))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SC_Common.SC_ErrorDetail)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Object))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(RPR0200SvcRef.RPR0200DTO01)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of RPR0200SvcRef.Repair_DetailDTO))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(RPR0200SvcRef.Repair_DetailDTO)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of RPR0200SvcRef.RPR0200DTO02))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(RPR0200SvcRef.RPR0200DTO02)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of RPR0200SvcRef.LKM_CompanyDTO))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(RPR0200SvcRef.LKM_CompanyDTO)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of RPR0200SvcRef.LKM_CompanyOfficeDTO))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(RPR0200SvcRef.LKM_CompanyOfficeDTO)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of RPR0200SvcRef.LKM_OutletDTO))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(RPR0200SvcRef.LKM_OutletDTO)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of RPR0200SvcRef.LKM_SparepartDTO))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(RPR0200SvcRef.LKM_SparepartDTO))>  _
        Function getOffice(ByVal poparam As System.Collections.Generic.List(Of Object)) As System.Collections.Generic.List(Of RPR0200SvcRef.LKM_CompanyOfficeDTO)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IRPR0200Svc/getOffice", ReplyAction:="http://tempuri.org/IRPR0200Svc/getOfficeResponse")>  _
        Function getOfficeAsync(ByVal poparam As System.Collections.Generic.List(Of Object)) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of RPR0200SvcRef.LKM_CompanyOfficeDTO))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IRPR0200Svc/getOutlet", ReplyAction:="http://tempuri.org/IRPR0200Svc/getOutletResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SC_Common.SC_ServiceExceptions), Action:="http://tempuri.org/IRPR0200Svc/getOutletSC_ServiceExceptionsFault", Name:="SC_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_Common"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(RPR0200SvcRef.SC_DTOBase)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(RPR0200SvcRef.eCRUDMode)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SC_Common.SC_ServiceExceptions)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of SC_Common.SC_Error))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SC_Common.SC_Error)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of SC_Common.SC_ErrorDetail))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SC_Common.SC_ErrorDetail)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Object))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(RPR0200SvcRef.RPR0200DTO01)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of RPR0200SvcRef.Repair_DetailDTO))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(RPR0200SvcRef.Repair_DetailDTO)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of RPR0200SvcRef.RPR0200DTO02))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(RPR0200SvcRef.RPR0200DTO02)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of RPR0200SvcRef.LKM_CompanyDTO))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(RPR0200SvcRef.LKM_CompanyDTO)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of RPR0200SvcRef.LKM_CompanyOfficeDTO))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(RPR0200SvcRef.LKM_CompanyOfficeDTO)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of RPR0200SvcRef.LKM_OutletDTO))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(RPR0200SvcRef.LKM_OutletDTO)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of RPR0200SvcRef.LKM_SparepartDTO))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(RPR0200SvcRef.LKM_SparepartDTO))>  _
        Function getOutlet(ByVal poparam As System.Collections.Generic.List(Of Object)) As System.Collections.Generic.List(Of RPR0200SvcRef.LKM_OutletDTO)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IRPR0200Svc/getOutlet", ReplyAction:="http://tempuri.org/IRPR0200Svc/getOutletResponse")>  _
        Function getOutletAsync(ByVal poparam As System.Collections.Generic.List(Of Object)) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of RPR0200SvcRef.LKM_OutletDTO))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IRPR0200Svc/getSparepart", ReplyAction:="http://tempuri.org/IRPR0200Svc/getSparepartResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SC_Common.SC_ServiceExceptions), Action:="http://tempuri.org/IRPR0200Svc/getSparepartSC_ServiceExceptionsFault", Name:="SC_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_Common")>  _
        Function getSparepart(ByVal KD_PART As String, ByVal CompanyOfficeID As String) As System.Collections.Generic.List(Of RPR0200SvcRef.LKM_SparepartDTO)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IRPR0200Svc/getSparepart", ReplyAction:="http://tempuri.org/IRPR0200Svc/getSparepartResponse")>  _
        Function getSparepartAsync(ByVal KD_PART As String, ByVal CompanyOfficeID As String) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of RPR0200SvcRef.LKM_SparepartDTO))
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IRPR0200SvcChannel
        Inherits RPR0200SvcRef.IRPR0200Svc, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class RPR0200SvcClient
        Inherits System.ServiceModel.ClientBase(Of RPR0200SvcRef.IRPR0200Svc)
        Implements RPR0200SvcRef.IRPR0200Svc
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Svc_SC_GetRecord(ByVal poEntity As RPR0200SvcRef.RPR0200DTO01, ByVal poCRUDMode As RPR0200SvcRef.eCRUDMode) As RPR0200SvcRef.RPR0200DTO01 Implements RPR0200SvcRef.IRPR0200Svc.Svc_SC_GetRecord
            Return MyBase.Channel.Svc_SC_GetRecord(poEntity, poCRUDMode)
        End Function
        
        Public Function Svc_SC_GetRecordAsync(ByVal poEntity As RPR0200SvcRef.RPR0200DTO01, ByVal poCRUDMode As RPR0200SvcRef.eCRUDMode) As System.Threading.Tasks.Task(Of RPR0200SvcRef.RPR0200DTO01) Implements RPR0200SvcRef.IRPR0200Svc.Svc_SC_GetRecordAsync
            Return MyBase.Channel.Svc_SC_GetRecordAsync(poEntity, poCRUDMode)
        End Function
        
        Public Function Svc_SC_Save(ByVal poEntity As RPR0200SvcRef.RPR0200DTO01, ByVal poCRUDMode As RPR0200SvcRef.eCRUDMode) As RPR0200SvcRef.RPR0200DTO01 Implements RPR0200SvcRef.IRPR0200Svc.Svc_SC_Save
            Return MyBase.Channel.Svc_SC_Save(poEntity, poCRUDMode)
        End Function
        
        Public Function Svc_SC_SaveAsync(ByVal poEntity As RPR0200SvcRef.RPR0200DTO01, ByVal poCRUDMode As RPR0200SvcRef.eCRUDMode) As System.Threading.Tasks.Task(Of RPR0200SvcRef.RPR0200DTO01) Implements RPR0200SvcRef.IRPR0200Svc.Svc_SC_SaveAsync
            Return MyBase.Channel.Svc_SC_SaveAsync(poEntity, poCRUDMode)
        End Function
        
        Public Sub Svc_SC_Delete(ByVal poEntity As RPR0200SvcRef.RPR0200DTO01) Implements RPR0200SvcRef.IRPR0200Svc.Svc_SC_Delete
            MyBase.Channel.Svc_SC_Delete(poEntity)
        End Sub
        
        Public Function Svc_SC_DeleteAsync(ByVal poEntity As RPR0200SvcRef.RPR0200DTO01) As System.Threading.Tasks.Task Implements RPR0200SvcRef.IRPR0200Svc.Svc_SC_DeleteAsync
            Return MyBase.Channel.Svc_SC_DeleteAsync(poEntity)
        End Function
        
        Public Function getList(ByVal poparam As System.Collections.Generic.List(Of Object)) As System.Collections.Generic.List(Of RPR0200SvcRef.RPR0200DTO02) Implements RPR0200SvcRef.IRPR0200Svc.getList
            Return MyBase.Channel.getList(poparam)
        End Function
        
        Public Function getListAsync(ByVal poparam As System.Collections.Generic.List(Of Object)) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of RPR0200SvcRef.RPR0200DTO02)) Implements RPR0200SvcRef.IRPR0200Svc.getListAsync
            Return MyBase.Channel.getListAsync(poparam)
        End Function
        
        Public Function getList_Detail(ByVal poparam As RPR0200SvcRef.RPR0200DTO01) As System.Collections.Generic.List(Of RPR0200SvcRef.Repair_DetailDTO) Implements RPR0200SvcRef.IRPR0200Svc.getList_Detail
            Return MyBase.Channel.getList_Detail(poparam)
        End Function
        
        Public Function getList_DetailAsync(ByVal poparam As RPR0200SvcRef.RPR0200DTO01) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of RPR0200SvcRef.Repair_DetailDTO)) Implements RPR0200SvcRef.IRPR0200Svc.getList_DetailAsync
            Return MyBase.Channel.getList_DetailAsync(poparam)
        End Function
        
        Public Function getCompany(ByVal poparam As System.Collections.Generic.List(Of Object)) As System.Collections.Generic.List(Of RPR0200SvcRef.LKM_CompanyDTO) Implements RPR0200SvcRef.IRPR0200Svc.getCompany
            Return MyBase.Channel.getCompany(poparam)
        End Function
        
        Public Function getCompanyAsync(ByVal poparam As System.Collections.Generic.List(Of Object)) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of RPR0200SvcRef.LKM_CompanyDTO)) Implements RPR0200SvcRef.IRPR0200Svc.getCompanyAsync
            Return MyBase.Channel.getCompanyAsync(poparam)
        End Function
        
        Public Function getOffice(ByVal poparam As System.Collections.Generic.List(Of Object)) As System.Collections.Generic.List(Of RPR0200SvcRef.LKM_CompanyOfficeDTO) Implements RPR0200SvcRef.IRPR0200Svc.getOffice
            Return MyBase.Channel.getOffice(poparam)
        End Function
        
        Public Function getOfficeAsync(ByVal poparam As System.Collections.Generic.List(Of Object)) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of RPR0200SvcRef.LKM_CompanyOfficeDTO)) Implements RPR0200SvcRef.IRPR0200Svc.getOfficeAsync
            Return MyBase.Channel.getOfficeAsync(poparam)
        End Function
        
        Public Function getOutlet(ByVal poparam As System.Collections.Generic.List(Of Object)) As System.Collections.Generic.List(Of RPR0200SvcRef.LKM_OutletDTO) Implements RPR0200SvcRef.IRPR0200Svc.getOutlet
            Return MyBase.Channel.getOutlet(poparam)
        End Function
        
        Public Function getOutletAsync(ByVal poparam As System.Collections.Generic.List(Of Object)) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of RPR0200SvcRef.LKM_OutletDTO)) Implements RPR0200SvcRef.IRPR0200Svc.getOutletAsync
            Return MyBase.Channel.getOutletAsync(poparam)
        End Function
        
        Public Function getSparepart(ByVal KD_PART As String, ByVal CompanyOfficeID As String) As System.Collections.Generic.List(Of RPR0200SvcRef.LKM_SparepartDTO) Implements RPR0200SvcRef.IRPR0200Svc.getSparepart
            Return MyBase.Channel.getSparepart(KD_PART, CompanyOfficeID)
        End Function
        
        Public Function getSparepartAsync(ByVal KD_PART As String, ByVal CompanyOfficeID As String) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of RPR0200SvcRef.LKM_SparepartDTO)) Implements RPR0200SvcRef.IRPR0200Svc.getSparepartAsync
            Return MyBase.Channel.getSparepartAsync(KD_PART, CompanyOfficeID)
        End Function
    End Class
End Namespace
