'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace MTN0100SvcRef
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SC_DTOBase", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_BackEnd"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(MTN0100SvcRef.MTN0100DTO01))>  _
    Partial Public Class SC_DTOBase
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MTN0100DTO01", [Namespace]:="http://schemas.datacontract.org/2004/07/MTN0100Back"),  _
     System.SerializableAttribute()>  _
    Partial Public Class MTN0100DTO01
        Inherits MTN0100SvcRef.SC_DTOBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BARCODEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private COMPANY_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private COMPANY_OFFICE_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CREA_BYField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CREA_DATEField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FROM_DATEField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MAINTENANCE_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OUTLET_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TO_DATEField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UPD_BYField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UPD_DATEField As Date
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BARCODE() As String
            Get
                Return Me.BARCODEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BARCODEField, value) <> true) Then
                    Me.BARCODEField = value
                    Me.RaisePropertyChanged("BARCODE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property COMPANY_ID() As String
            Get
                Return Me.COMPANY_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.COMPANY_IDField, value) <> true) Then
                    Me.COMPANY_IDField = value
                    Me.RaisePropertyChanged("COMPANY_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property COMPANY_OFFICE_ID() As String
            Get
                Return Me.COMPANY_OFFICE_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.COMPANY_OFFICE_IDField, value) <> true) Then
                    Me.COMPANY_OFFICE_IDField = value
                    Me.RaisePropertyChanged("COMPANY_OFFICE_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CREA_BY() As String
            Get
                Return Me.CREA_BYField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CREA_BYField, value) <> true) Then
                    Me.CREA_BYField = value
                    Me.RaisePropertyChanged("CREA_BY")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CREA_DATE() As Date
            Get
                Return Me.CREA_DATEField
            End Get
            Set
                If (Me.CREA_DATEField.Equals(value) <> true) Then
                    Me.CREA_DATEField = value
                    Me.RaisePropertyChanged("CREA_DATE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FROM_DATE() As Date
            Get
                Return Me.FROM_DATEField
            End Get
            Set
                If (Me.FROM_DATEField.Equals(value) <> true) Then
                    Me.FROM_DATEField = value
                    Me.RaisePropertyChanged("FROM_DATE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MAINTENANCE_ID() As String
            Get
                Return Me.MAINTENANCE_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MAINTENANCE_IDField, value) <> true) Then
                    Me.MAINTENANCE_IDField = value
                    Me.RaisePropertyChanged("MAINTENANCE_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OUTLET_ID() As String
            Get
                Return Me.OUTLET_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OUTLET_IDField, value) <> true) Then
                    Me.OUTLET_IDField = value
                    Me.RaisePropertyChanged("OUTLET_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TO_DATE() As Date
            Get
                Return Me.TO_DATEField
            End Get
            Set
                If (Me.TO_DATEField.Equals(value) <> true) Then
                    Me.TO_DATEField = value
                    Me.RaisePropertyChanged("TO_DATE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UPD_BY() As String
            Get
                Return Me.UPD_BYField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UPD_BYField, value) <> true) Then
                    Me.UPD_BYField = value
                    Me.RaisePropertyChanged("UPD_BY")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UPD_DATE() As Date
            Get
                Return Me.UPD_DATEField
            End Get
            Set
                If (Me.UPD_DATEField.Equals(value) <> true) Then
                    Me.UPD_DATEField = value
                    Me.RaisePropertyChanged("UPD_DATE")
                End If
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="eCRUDMode", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_BackEnd")>  _
    Public Enum eCRUDMode As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        NormalMode = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        AddMode = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        EditMode = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        DeleteMode = 3
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MTN0100DTO02", [Namespace]:="http://schemas.datacontract.org/2004/07/MTN0100Back"),  _
     System.SerializableAttribute()>  _
    Partial Public Class MTN0100DTO02
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BARCODEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private COMPANY_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private COMPANY_OFFICE_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CREA_BYField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CREA_DATEField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FROM_DATEField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MAINTENANCE_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OUTLET_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TO_DATEField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UPD_BYField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UPD_DATEField As Date
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BARCODE() As String
            Get
                Return Me.BARCODEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BARCODEField, value) <> true) Then
                    Me.BARCODEField = value
                    Me.RaisePropertyChanged("BARCODE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property COMPANY_ID() As String
            Get
                Return Me.COMPANY_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.COMPANY_IDField, value) <> true) Then
                    Me.COMPANY_IDField = value
                    Me.RaisePropertyChanged("COMPANY_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property COMPANY_OFFICE_ID() As String
            Get
                Return Me.COMPANY_OFFICE_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.COMPANY_OFFICE_IDField, value) <> true) Then
                    Me.COMPANY_OFFICE_IDField = value
                    Me.RaisePropertyChanged("COMPANY_OFFICE_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CREA_BY() As String
            Get
                Return Me.CREA_BYField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CREA_BYField, value) <> true) Then
                    Me.CREA_BYField = value
                    Me.RaisePropertyChanged("CREA_BY")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CREA_DATE() As Date
            Get
                Return Me.CREA_DATEField
            End Get
            Set
                If (Me.CREA_DATEField.Equals(value) <> true) Then
                    Me.CREA_DATEField = value
                    Me.RaisePropertyChanged("CREA_DATE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FROM_DATE() As Date
            Get
                Return Me.FROM_DATEField
            End Get
            Set
                If (Me.FROM_DATEField.Equals(value) <> true) Then
                    Me.FROM_DATEField = value
                    Me.RaisePropertyChanged("FROM_DATE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MAINTENANCE_ID() As String
            Get
                Return Me.MAINTENANCE_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MAINTENANCE_IDField, value) <> true) Then
                    Me.MAINTENANCE_IDField = value
                    Me.RaisePropertyChanged("MAINTENANCE_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OUTLET_ID() As String
            Get
                Return Me.OUTLET_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OUTLET_IDField, value) <> true) Then
                    Me.OUTLET_IDField = value
                    Me.RaisePropertyChanged("OUTLET_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TO_DATE() As Date
            Get
                Return Me.TO_DATEField
            End Get
            Set
                If (Me.TO_DATEField.Equals(value) <> true) Then
                    Me.TO_DATEField = value
                    Me.RaisePropertyChanged("TO_DATE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UPD_BY() As String
            Get
                Return Me.UPD_BYField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UPD_BYField, value) <> true) Then
                    Me.UPD_BYField = value
                    Me.RaisePropertyChanged("UPD_BY")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UPD_DATE() As Date
            Get
                Return Me.UPD_DATEField
            End Get
            Set
                If (Me.UPD_DATEField.Equals(value) <> true) Then
                    Me.UPD_DATEField = value
                    Me.RaisePropertyChanged("UPD_DATE")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Maintenance_DetailDTO", [Namespace]:="http://schemas.datacontract.org/2004/07/MTN0100Back"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Maintenance_DetailDTO
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BROKENField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CASE_IDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CREA_BYField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CREA_DATEField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private GOODField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MAINTENANCE_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MAJORField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MINORField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UPD_BYField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UPD_DATEField As Date
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BROKEN() As Boolean
            Get
                Return Me.BROKENField
            End Get
            Set
                If (Me.BROKENField.Equals(value) <> true) Then
                    Me.BROKENField = value
                    Me.RaisePropertyChanged("BROKEN")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CASE_ID() As Integer
            Get
                Return Me.CASE_IDField
            End Get
            Set
                If (Me.CASE_IDField.Equals(value) <> true) Then
                    Me.CASE_IDField = value
                    Me.RaisePropertyChanged("CASE_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CREA_BY() As String
            Get
                Return Me.CREA_BYField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CREA_BYField, value) <> true) Then
                    Me.CREA_BYField = value
                    Me.RaisePropertyChanged("CREA_BY")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CREA_DATE() As Date
            Get
                Return Me.CREA_DATEField
            End Get
            Set
                If (Me.CREA_DATEField.Equals(value) <> true) Then
                    Me.CREA_DATEField = value
                    Me.RaisePropertyChanged("CREA_DATE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property GOOD() As Boolean
            Get
                Return Me.GOODField
            End Get
            Set
                If (Me.GOODField.Equals(value) <> true) Then
                    Me.GOODField = value
                    Me.RaisePropertyChanged("GOOD")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MAINTENANCE_ID() As String
            Get
                Return Me.MAINTENANCE_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MAINTENANCE_IDField, value) <> true) Then
                    Me.MAINTENANCE_IDField = value
                    Me.RaisePropertyChanged("MAINTENANCE_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MAJOR() As Boolean
            Get
                Return Me.MAJORField
            End Get
            Set
                If (Me.MAJORField.Equals(value) <> true) Then
                    Me.MAJORField = value
                    Me.RaisePropertyChanged("MAJOR")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MINOR() As Boolean
            Get
                Return Me.MINORField
            End Get
            Set
                If (Me.MINORField.Equals(value) <> true) Then
                    Me.MINORField = value
                    Me.RaisePropertyChanged("MINOR")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UPD_BY() As String
            Get
                Return Me.UPD_BYField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UPD_BYField, value) <> true) Then
                    Me.UPD_BYField = value
                    Me.RaisePropertyChanged("UPD_BY")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UPD_DATE() As Date
            Get
                Return Me.UPD_DATEField
            End Get
            Set
                If (Me.UPD_DATEField.Equals(value) <> true) Then
                    Me.UPD_DATEField = value
                    Me.RaisePropertyChanged("UPD_DATE")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LKM_CompanyDTO", [Namespace]:="http://schemas.datacontract.org/2004/07/MTN0100Back"),  _
     System.SerializableAttribute()>  _
    Partial Public Class LKM_CompanyDTO
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private COMPANY_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private COMPANY_NAMEField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property COMPANY_ID() As String
            Get
                Return Me.COMPANY_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.COMPANY_IDField, value) <> true) Then
                    Me.COMPANY_IDField = value
                    Me.RaisePropertyChanged("COMPANY_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property COMPANY_NAME() As String
            Get
                Return Me.COMPANY_NAMEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.COMPANY_NAMEField, value) <> true) Then
                    Me.COMPANY_NAMEField = value
                    Me.RaisePropertyChanged("COMPANY_NAME")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LKM_CompanyOfficeDTO", [Namespace]:="http://schemas.datacontract.org/2004/07/MTN0100Back"),  _
     System.SerializableAttribute()>  _
    Partial Public Class LKM_CompanyOfficeDTO
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private COMPANY_OFFICEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private COMPANY_OFFICE_IDField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property COMPANY_OFFICE() As String
            Get
                Return Me.COMPANY_OFFICEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.COMPANY_OFFICEField, value) <> true) Then
                    Me.COMPANY_OFFICEField = value
                    Me.RaisePropertyChanged("COMPANY_OFFICE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property COMPANY_OFFICE_ID() As String
            Get
                Return Me.COMPANY_OFFICE_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.COMPANY_OFFICE_IDField, value) <> true) Then
                    Me.COMPANY_OFFICE_IDField = value
                    Me.RaisePropertyChanged("COMPANY_OFFICE_ID")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="MTN0100SvcRef.IMTN0100Svc")>  _
    Public Interface IMTN0100Svc
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SC_IServicebaseOf_MTN0100DTO01/Svc_SC_GetRecord", ReplyAction:="http://tempuri.org/SC_IServicebaseOf_MTN0100DTO01/Svc_SC_GetRecordResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SC_Common.SC_ServiceExceptions), Action:="http://tempuri.org/SC_IServicebaseOf_MTN0100DTO01/Svc_SC_GetRecordSC_ServiceExcep"& _ 
            "tionsFault", Name:="SC_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_Common")>  _
        Function Svc_SC_GetRecord(ByVal poEntity As MTN0100SvcRef.MTN0100DTO01, ByVal poCRUDMode As MTN0100SvcRef.eCRUDMode) As MTN0100SvcRef.MTN0100DTO01
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SC_IServicebaseOf_MTN0100DTO01/Svc_SC_GetRecord", ReplyAction:="http://tempuri.org/SC_IServicebaseOf_MTN0100DTO01/Svc_SC_GetRecordResponse")>  _
        Function Svc_SC_GetRecordAsync(ByVal poEntity As MTN0100SvcRef.MTN0100DTO01, ByVal poCRUDMode As MTN0100SvcRef.eCRUDMode) As System.Threading.Tasks.Task(Of MTN0100SvcRef.MTN0100DTO01)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SC_IServicebaseOf_MTN0100DTO01/Svc_SC_Save", ReplyAction:="http://tempuri.org/SC_IServicebaseOf_MTN0100DTO01/Svc_SC_SaveResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SC_Common.SC_ServiceExceptions), Action:="http://tempuri.org/SC_IServicebaseOf_MTN0100DTO01/Svc_SC_SaveSC_ServiceExceptions"& _ 
            "Fault", Name:="SC_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_Common")>  _
        Function Svc_SC_Save(ByVal poEntity As MTN0100SvcRef.MTN0100DTO01, ByVal poCRUDMode As MTN0100SvcRef.eCRUDMode) As MTN0100SvcRef.MTN0100DTO01
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SC_IServicebaseOf_MTN0100DTO01/Svc_SC_Save", ReplyAction:="http://tempuri.org/SC_IServicebaseOf_MTN0100DTO01/Svc_SC_SaveResponse")>  _
        Function Svc_SC_SaveAsync(ByVal poEntity As MTN0100SvcRef.MTN0100DTO01, ByVal poCRUDMode As MTN0100SvcRef.eCRUDMode) As System.Threading.Tasks.Task(Of MTN0100SvcRef.MTN0100DTO01)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SC_IServicebaseOf_MTN0100DTO01/Svc_SC_Delete", ReplyAction:="http://tempuri.org/SC_IServicebaseOf_MTN0100DTO01/Svc_SC_DeleteResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SC_Common.SC_ServiceExceptions), Action:="http://tempuri.org/SC_IServicebaseOf_MTN0100DTO01/Svc_SC_DeleteSC_ServiceExceptio"& _ 
            "nsFault", Name:="SC_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_Common")>  _
        Sub Svc_SC_Delete(ByVal poEntity As MTN0100SvcRef.MTN0100DTO01)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SC_IServicebaseOf_MTN0100DTO01/Svc_SC_Delete", ReplyAction:="http://tempuri.org/SC_IServicebaseOf_MTN0100DTO01/Svc_SC_DeleteResponse")>  _
        Function Svc_SC_DeleteAsync(ByVal poEntity As MTN0100SvcRef.MTN0100DTO01) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMTN0100Svc/getList", ReplyAction:="http://tempuri.org/IMTN0100Svc/getListResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SC_Common.SC_ServiceExceptions), Action:="http://tempuri.org/IMTN0100Svc/getListSC_ServiceExceptionsFault", Name:="SC_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_Common"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SC_Common.SC_ServiceExceptions)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of SC_Common.SC_Error))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SC_Common.SC_Error)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of SC_Common.SC_ErrorDetail))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SC_Common.SC_ErrorDetail)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Object))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MTN0100SvcRef.MTN0100DTO01)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of MTN0100SvcRef.MTN0100DTO02))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MTN0100SvcRef.MTN0100DTO02)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of MTN0100SvcRef.Maintenance_DetailDTO))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MTN0100SvcRef.Maintenance_DetailDTO)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of MTN0100SvcRef.LKM_CompanyDTO))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MTN0100SvcRef.LKM_CompanyDTO)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of MTN0100SvcRef.LKM_CompanyOfficeDTO))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MTN0100SvcRef.LKM_CompanyOfficeDTO)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MTN0100SvcRef.SC_DTOBase)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MTN0100SvcRef.eCRUDMode))>  _
        Function getList(ByVal poParam As System.Collections.Generic.List(Of Object)) As System.Collections.Generic.List(Of MTN0100SvcRef.MTN0100DTO02)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMTN0100Svc/getList", ReplyAction:="http://tempuri.org/IMTN0100Svc/getListResponse")>  _
        Function getListAsync(ByVal poParam As System.Collections.Generic.List(Of Object)) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of MTN0100SvcRef.MTN0100DTO02))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMTN0100Svc/getList_Detail", ReplyAction:="http://tempuri.org/IMTN0100Svc/getList_DetailResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SC_Common.SC_ServiceExceptions), Action:="http://tempuri.org/IMTN0100Svc/getList_DetailSC_ServiceExceptionsFault", Name:="SC_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_Common")>  _
        Function getList_Detail(ByVal poParam As MTN0100SvcRef.MTN0100DTO01) As System.Collections.Generic.List(Of MTN0100SvcRef.Maintenance_DetailDTO)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMTN0100Svc/getList_Detail", ReplyAction:="http://tempuri.org/IMTN0100Svc/getList_DetailResponse")>  _
        Function getList_DetailAsync(ByVal poParam As MTN0100SvcRef.MTN0100DTO01) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of MTN0100SvcRef.Maintenance_DetailDTO))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMTN0100Svc/getCompany", ReplyAction:="http://tempuri.org/IMTN0100Svc/getCompanyResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SC_Common.SC_ServiceExceptions), Action:="http://tempuri.org/IMTN0100Svc/getCompanySC_ServiceExceptionsFault", Name:="SC_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_Common"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SC_Common.SC_ServiceExceptions)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of SC_Common.SC_Error))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SC_Common.SC_Error)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of SC_Common.SC_ErrorDetail))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SC_Common.SC_ErrorDetail)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Object))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MTN0100SvcRef.MTN0100DTO01)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of MTN0100SvcRef.MTN0100DTO02))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MTN0100SvcRef.MTN0100DTO02)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of MTN0100SvcRef.Maintenance_DetailDTO))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MTN0100SvcRef.Maintenance_DetailDTO)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of MTN0100SvcRef.LKM_CompanyDTO))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MTN0100SvcRef.LKM_CompanyDTO)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of MTN0100SvcRef.LKM_CompanyOfficeDTO))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MTN0100SvcRef.LKM_CompanyOfficeDTO)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MTN0100SvcRef.SC_DTOBase)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MTN0100SvcRef.eCRUDMode))>  _
        Function getCompany(ByVal poParam As System.Collections.Generic.List(Of Object)) As System.Collections.Generic.List(Of MTN0100SvcRef.LKM_CompanyDTO)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMTN0100Svc/getCompany", ReplyAction:="http://tempuri.org/IMTN0100Svc/getCompanyResponse")>  _
        Function getCompanyAsync(ByVal poParam As System.Collections.Generic.List(Of Object)) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of MTN0100SvcRef.LKM_CompanyDTO))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMTN0100Svc/getOffice", ReplyAction:="http://tempuri.org/IMTN0100Svc/getOfficeResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SC_Common.SC_ServiceExceptions), Action:="http://tempuri.org/IMTN0100Svc/getOfficeSC_ServiceExceptionsFault", Name:="SC_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_Common"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SC_Common.SC_ServiceExceptions)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of SC_Common.SC_Error))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SC_Common.SC_Error)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of SC_Common.SC_ErrorDetail))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SC_Common.SC_ErrorDetail)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Object))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MTN0100SvcRef.MTN0100DTO01)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of MTN0100SvcRef.MTN0100DTO02))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MTN0100SvcRef.MTN0100DTO02)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of MTN0100SvcRef.Maintenance_DetailDTO))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MTN0100SvcRef.Maintenance_DetailDTO)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of MTN0100SvcRef.LKM_CompanyDTO))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MTN0100SvcRef.LKM_CompanyDTO)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of MTN0100SvcRef.LKM_CompanyOfficeDTO))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MTN0100SvcRef.LKM_CompanyOfficeDTO)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MTN0100SvcRef.SC_DTOBase)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MTN0100SvcRef.eCRUDMode))>  _
        Function getOffice(ByVal poParam As System.Collections.Generic.List(Of Object)) As System.Collections.Generic.List(Of MTN0100SvcRef.LKM_CompanyOfficeDTO)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMTN0100Svc/getOffice", ReplyAction:="http://tempuri.org/IMTN0100Svc/getOfficeResponse")>  _
        Function getOfficeAsync(ByVal poParam As System.Collections.Generic.List(Of Object)) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of MTN0100SvcRef.LKM_CompanyOfficeDTO))
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IMTN0100SvcChannel
        Inherits MTN0100SvcRef.IMTN0100Svc, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class MTN0100SvcClient
        Inherits System.ServiceModel.ClientBase(Of MTN0100SvcRef.IMTN0100Svc)
        Implements MTN0100SvcRef.IMTN0100Svc
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Svc_SC_GetRecord(ByVal poEntity As MTN0100SvcRef.MTN0100DTO01, ByVal poCRUDMode As MTN0100SvcRef.eCRUDMode) As MTN0100SvcRef.MTN0100DTO01 Implements MTN0100SvcRef.IMTN0100Svc.Svc_SC_GetRecord
            Return MyBase.Channel.Svc_SC_GetRecord(poEntity, poCRUDMode)
        End Function
        
        Public Function Svc_SC_GetRecordAsync(ByVal poEntity As MTN0100SvcRef.MTN0100DTO01, ByVal poCRUDMode As MTN0100SvcRef.eCRUDMode) As System.Threading.Tasks.Task(Of MTN0100SvcRef.MTN0100DTO01) Implements MTN0100SvcRef.IMTN0100Svc.Svc_SC_GetRecordAsync
            Return MyBase.Channel.Svc_SC_GetRecordAsync(poEntity, poCRUDMode)
        End Function
        
        Public Function Svc_SC_Save(ByVal poEntity As MTN0100SvcRef.MTN0100DTO01, ByVal poCRUDMode As MTN0100SvcRef.eCRUDMode) As MTN0100SvcRef.MTN0100DTO01 Implements MTN0100SvcRef.IMTN0100Svc.Svc_SC_Save
            Return MyBase.Channel.Svc_SC_Save(poEntity, poCRUDMode)
        End Function
        
        Public Function Svc_SC_SaveAsync(ByVal poEntity As MTN0100SvcRef.MTN0100DTO01, ByVal poCRUDMode As MTN0100SvcRef.eCRUDMode) As System.Threading.Tasks.Task(Of MTN0100SvcRef.MTN0100DTO01) Implements MTN0100SvcRef.IMTN0100Svc.Svc_SC_SaveAsync
            Return MyBase.Channel.Svc_SC_SaveAsync(poEntity, poCRUDMode)
        End Function
        
        Public Sub Svc_SC_Delete(ByVal poEntity As MTN0100SvcRef.MTN0100DTO01) Implements MTN0100SvcRef.IMTN0100Svc.Svc_SC_Delete
            MyBase.Channel.Svc_SC_Delete(poEntity)
        End Sub
        
        Public Function Svc_SC_DeleteAsync(ByVal poEntity As MTN0100SvcRef.MTN0100DTO01) As System.Threading.Tasks.Task Implements MTN0100SvcRef.IMTN0100Svc.Svc_SC_DeleteAsync
            Return MyBase.Channel.Svc_SC_DeleteAsync(poEntity)
        End Function
        
        Public Function getList(ByVal poParam As System.Collections.Generic.List(Of Object)) As System.Collections.Generic.List(Of MTN0100SvcRef.MTN0100DTO02) Implements MTN0100SvcRef.IMTN0100Svc.getList
            Return MyBase.Channel.getList(poParam)
        End Function
        
        Public Function getListAsync(ByVal poParam As System.Collections.Generic.List(Of Object)) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of MTN0100SvcRef.MTN0100DTO02)) Implements MTN0100SvcRef.IMTN0100Svc.getListAsync
            Return MyBase.Channel.getListAsync(poParam)
        End Function
        
        Public Function getList_Detail(ByVal poParam As MTN0100SvcRef.MTN0100DTO01) As System.Collections.Generic.List(Of MTN0100SvcRef.Maintenance_DetailDTO) Implements MTN0100SvcRef.IMTN0100Svc.getList_Detail
            Return MyBase.Channel.getList_Detail(poParam)
        End Function
        
        Public Function getList_DetailAsync(ByVal poParam As MTN0100SvcRef.MTN0100DTO01) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of MTN0100SvcRef.Maintenance_DetailDTO)) Implements MTN0100SvcRef.IMTN0100Svc.getList_DetailAsync
            Return MyBase.Channel.getList_DetailAsync(poParam)
        End Function
        
        Public Function getCompany(ByVal poParam As System.Collections.Generic.List(Of Object)) As System.Collections.Generic.List(Of MTN0100SvcRef.LKM_CompanyDTO) Implements MTN0100SvcRef.IMTN0100Svc.getCompany
            Return MyBase.Channel.getCompany(poParam)
        End Function
        
        Public Function getCompanyAsync(ByVal poParam As System.Collections.Generic.List(Of Object)) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of MTN0100SvcRef.LKM_CompanyDTO)) Implements MTN0100SvcRef.IMTN0100Svc.getCompanyAsync
            Return MyBase.Channel.getCompanyAsync(poParam)
        End Function
        
        Public Function getOffice(ByVal poParam As System.Collections.Generic.List(Of Object)) As System.Collections.Generic.List(Of MTN0100SvcRef.LKM_CompanyOfficeDTO) Implements MTN0100SvcRef.IMTN0100Svc.getOffice
            Return MyBase.Channel.getOffice(poParam)
        End Function
        
        Public Function getOfficeAsync(ByVal poParam As System.Collections.Generic.List(Of Object)) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of MTN0100SvcRef.LKM_CompanyOfficeDTO)) Implements MTN0100SvcRef.IMTN0100Svc.getOfficeAsync
            Return MyBase.Channel.getOfficeAsync(poParam)
        End Function
    End Class
End Namespace
