'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace SYS0300SvcRef
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SC_DTOBase", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_BackEnd"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(SYS0300SvcRef.SYS0300DTO01))>  _
    Partial Public Class SC_DTOBase
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SYS0300DTO01", [Namespace]:="http://schemas.datacontract.org/2004/07/SYS0300Back"),  _
     System.SerializableAttribute()>  _
    Partial Public Class SYS0300DTO01
        Inherits SYS0300SvcRef.SC_DTOBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private APP_DESCField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private APP_GROUP_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private APP_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private APP_NAMEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private APP_TYPEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CREA_BYField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CREA_DATEField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DLL_FILEField() As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DLL_FILE_VERSIONField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MODULE_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UPDATE_DLL_FILEField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UPD_BYField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UPD_DATEField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private VERSIONField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property APP_DESC() As String
            Get
                Return Me.APP_DESCField
            End Get
            Set
                If (Object.ReferenceEquals(Me.APP_DESCField, value) <> true) Then
                    Me.APP_DESCField = value
                    Me.RaisePropertyChanged("APP_DESC")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property APP_GROUP_ID() As String
            Get
                Return Me.APP_GROUP_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.APP_GROUP_IDField, value) <> true) Then
                    Me.APP_GROUP_IDField = value
                    Me.RaisePropertyChanged("APP_GROUP_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property APP_ID() As String
            Get
                Return Me.APP_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.APP_IDField, value) <> true) Then
                    Me.APP_IDField = value
                    Me.RaisePropertyChanged("APP_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property APP_NAME() As String
            Get
                Return Me.APP_NAMEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.APP_NAMEField, value) <> true) Then
                    Me.APP_NAMEField = value
                    Me.RaisePropertyChanged("APP_NAME")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property APP_TYPE() As String
            Get
                Return Me.APP_TYPEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.APP_TYPEField, value) <> true) Then
                    Me.APP_TYPEField = value
                    Me.RaisePropertyChanged("APP_TYPE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CREA_BY() As String
            Get
                Return Me.CREA_BYField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CREA_BYField, value) <> true) Then
                    Me.CREA_BYField = value
                    Me.RaisePropertyChanged("CREA_BY")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CREA_DATE() As Date
            Get
                Return Me.CREA_DATEField
            End Get
            Set
                If (Me.CREA_DATEField.Equals(value) <> true) Then
                    Me.CREA_DATEField = value
                    Me.RaisePropertyChanged("CREA_DATE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DLL_FILE() As Byte()
            Get
                Return Me.DLL_FILEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DLL_FILEField, value) <> true) Then
                    Me.DLL_FILEField = value
                    Me.RaisePropertyChanged("DLL_FILE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DLL_FILE_VERSION() As String
            Get
                Return Me.DLL_FILE_VERSIONField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DLL_FILE_VERSIONField, value) <> true) Then
                    Me.DLL_FILE_VERSIONField = value
                    Me.RaisePropertyChanged("DLL_FILE_VERSION")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MODULE_ID() As String
            Get
                Return Me.MODULE_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MODULE_IDField, value) <> true) Then
                    Me.MODULE_IDField = value
                    Me.RaisePropertyChanged("MODULE_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UPDATE_DLL_FILE() As Boolean
            Get
                Return Me.UPDATE_DLL_FILEField
            End Get
            Set
                If (Me.UPDATE_DLL_FILEField.Equals(value) <> true) Then
                    Me.UPDATE_DLL_FILEField = value
                    Me.RaisePropertyChanged("UPDATE_DLL_FILE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UPD_BY() As String
            Get
                Return Me.UPD_BYField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UPD_BYField, value) <> true) Then
                    Me.UPD_BYField = value
                    Me.RaisePropertyChanged("UPD_BY")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UPD_DATE() As Date
            Get
                Return Me.UPD_DATEField
            End Get
            Set
                If (Me.UPD_DATEField.Equals(value) <> true) Then
                    Me.UPD_DATEField = value
                    Me.RaisePropertyChanged("UPD_DATE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property VERSION() As String
            Get
                Return Me.VERSIONField
            End Get
            Set
                If (Object.ReferenceEquals(Me.VERSIONField, value) <> true) Then
                    Me.VERSIONField = value
                    Me.RaisePropertyChanged("VERSION")
                End If
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="eCRUDMode", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_BackEnd")>  _
    Public Enum eCRUDMode As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        NormalMode = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        AddMode = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        EditMode = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        DeleteMode = 3
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SYS0300DTO02", [Namespace]:="http://schemas.datacontract.org/2004/07/SYS0300Back"),  _
     System.SerializableAttribute()>  _
    Partial Public Class SYS0300DTO02
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private APP_DESCField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private APP_GROUP_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private APP_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private APP_NAMEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private APP_TYPEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CREA_BYField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CREA_DATEField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MODULE_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UPD_BYField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UPD_DATEField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private VERSIONField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property APP_DESC() As String
            Get
                Return Me.APP_DESCField
            End Get
            Set
                If (Object.ReferenceEquals(Me.APP_DESCField, value) <> true) Then
                    Me.APP_DESCField = value
                    Me.RaisePropertyChanged("APP_DESC")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property APP_GROUP_ID() As String
            Get
                Return Me.APP_GROUP_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.APP_GROUP_IDField, value) <> true) Then
                    Me.APP_GROUP_IDField = value
                    Me.RaisePropertyChanged("APP_GROUP_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property APP_ID() As String
            Get
                Return Me.APP_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.APP_IDField, value) <> true) Then
                    Me.APP_IDField = value
                    Me.RaisePropertyChanged("APP_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property APP_NAME() As String
            Get
                Return Me.APP_NAMEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.APP_NAMEField, value) <> true) Then
                    Me.APP_NAMEField = value
                    Me.RaisePropertyChanged("APP_NAME")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property APP_TYPE() As String
            Get
                Return Me.APP_TYPEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.APP_TYPEField, value) <> true) Then
                    Me.APP_TYPEField = value
                    Me.RaisePropertyChanged("APP_TYPE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CREA_BY() As String
            Get
                Return Me.CREA_BYField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CREA_BYField, value) <> true) Then
                    Me.CREA_BYField = value
                    Me.RaisePropertyChanged("CREA_BY")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CREA_DATE() As Date
            Get
                Return Me.CREA_DATEField
            End Get
            Set
                If (Me.CREA_DATEField.Equals(value) <> true) Then
                    Me.CREA_DATEField = value
                    Me.RaisePropertyChanged("CREA_DATE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MODULE_ID() As String
            Get
                Return Me.MODULE_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MODULE_IDField, value) <> true) Then
                    Me.MODULE_IDField = value
                    Me.RaisePropertyChanged("MODULE_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UPD_BY() As String
            Get
                Return Me.UPD_BYField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UPD_BYField, value) <> true) Then
                    Me.UPD_BYField = value
                    Me.RaisePropertyChanged("UPD_BY")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UPD_DATE() As Date
            Get
                Return Me.UPD_DATEField
            End Get
            Set
                If (Me.UPD_DATEField.Equals(value) <> true) Then
                    Me.UPD_DATEField = value
                    Me.RaisePropertyChanged("UPD_DATE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property VERSION() As String
            Get
                Return Me.VERSIONField
            End Get
            Set
                If (Object.ReferenceEquals(Me.VERSIONField, value) <> true) Then
                    Me.VERSIONField = value
                    Me.RaisePropertyChanged("VERSION")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LKM_SysModuleDTO", [Namespace]:="http://schemas.datacontract.org/2004/07/SYS0300Back"),  _
     System.SerializableAttribute()>  _
    Partial Public Class LKM_SysModuleDTO
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MODULE_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MODULE_NAMEField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MODULE_ID() As String
            Get
                Return Me.MODULE_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MODULE_IDField, value) <> true) Then
                    Me.MODULE_IDField = value
                    Me.RaisePropertyChanged("MODULE_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MODULE_NAME() As String
            Get
                Return Me.MODULE_NAMEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MODULE_NAMEField, value) <> true) Then
                    Me.MODULE_NAMEField = value
                    Me.RaisePropertyChanged("MODULE_NAME")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LKM_SysAppGroupDTO", [Namespace]:="http://schemas.datacontract.org/2004/07/SYS0300Back"),  _
     System.SerializableAttribute()>  _
    Partial Public Class LKM_SysAppGroupDTO
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private APP_GROUP_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private APP_GROUP_NAMEField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property APP_GROUP_ID() As String
            Get
                Return Me.APP_GROUP_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.APP_GROUP_IDField, value) <> true) Then
                    Me.APP_GROUP_IDField = value
                    Me.RaisePropertyChanged("APP_GROUP_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property APP_GROUP_NAME() As String
            Get
                Return Me.APP_GROUP_NAMEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.APP_GROUP_NAMEField, value) <> true) Then
                    Me.APP_GROUP_NAMEField = value
                    Me.RaisePropertyChanged("APP_GROUP_NAME")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LKM_SysAppTypeDTO", [Namespace]:="http://schemas.datacontract.org/2004/07/SYS0300Back"),  _
     System.SerializableAttribute()>  _
    Partial Public Class LKM_SysAppTypeDTO
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PARAMETER_VALUEField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PARAMETER_VALUE() As String
            Get
                Return Me.PARAMETER_VALUEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PARAMETER_VALUEField, value) <> true) Then
                    Me.PARAMETER_VALUEField = value
                    Me.RaisePropertyChanged("PARAMETER_VALUE")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="SYS0300SvcRef.ISYS0300Svc")>  _
    Public Interface ISYS0300Svc
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SC_IServicebaseOf_SYS0300DTO01/Svc_SC_GetRecord", ReplyAction:="http://tempuri.org/SC_IServicebaseOf_SYS0300DTO01/Svc_SC_GetRecordResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SC_Common.SC_ServiceExceptions), Action:="http://tempuri.org/SC_IServicebaseOf_SYS0300DTO01/Svc_SC_GetRecordSC_ServiceExcep"& _ 
            "tionsFault", Name:="SC_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_Common")>  _
        Function Svc_SC_GetRecord(ByVal poEntity As SYS0300SvcRef.SYS0300DTO01, ByVal poCRUDMode As SYS0300SvcRef.eCRUDMode) As SYS0300SvcRef.SYS0300DTO01
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SC_IServicebaseOf_SYS0300DTO01/Svc_SC_GetRecord", ReplyAction:="http://tempuri.org/SC_IServicebaseOf_SYS0300DTO01/Svc_SC_GetRecordResponse")>  _
        Function Svc_SC_GetRecordAsync(ByVal poEntity As SYS0300SvcRef.SYS0300DTO01, ByVal poCRUDMode As SYS0300SvcRef.eCRUDMode) As System.Threading.Tasks.Task(Of SYS0300SvcRef.SYS0300DTO01)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SC_IServicebaseOf_SYS0300DTO01/Svc_SC_Save", ReplyAction:="http://tempuri.org/SC_IServicebaseOf_SYS0300DTO01/Svc_SC_SaveResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SC_Common.SC_ServiceExceptions), Action:="http://tempuri.org/SC_IServicebaseOf_SYS0300DTO01/Svc_SC_SaveSC_ServiceExceptions"& _ 
            "Fault", Name:="SC_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_Common")>  _
        Function Svc_SC_Save(ByVal poEntity As SYS0300SvcRef.SYS0300DTO01, ByVal poCRUDMode As SYS0300SvcRef.eCRUDMode) As SYS0300SvcRef.SYS0300DTO01
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SC_IServicebaseOf_SYS0300DTO01/Svc_SC_Save", ReplyAction:="http://tempuri.org/SC_IServicebaseOf_SYS0300DTO01/Svc_SC_SaveResponse")>  _
        Function Svc_SC_SaveAsync(ByVal poEntity As SYS0300SvcRef.SYS0300DTO01, ByVal poCRUDMode As SYS0300SvcRef.eCRUDMode) As System.Threading.Tasks.Task(Of SYS0300SvcRef.SYS0300DTO01)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SC_IServicebaseOf_SYS0300DTO01/Svc_SC_Delete", ReplyAction:="http://tempuri.org/SC_IServicebaseOf_SYS0300DTO01/Svc_SC_DeleteResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SC_Common.SC_ServiceExceptions), Action:="http://tempuri.org/SC_IServicebaseOf_SYS0300DTO01/Svc_SC_DeleteSC_ServiceExceptio"& _ 
            "nsFault", Name:="SC_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_Common")>  _
        Sub Svc_SC_Delete(ByVal poEntity As SYS0300SvcRef.SYS0300DTO01)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SC_IServicebaseOf_SYS0300DTO01/Svc_SC_Delete", ReplyAction:="http://tempuri.org/SC_IServicebaseOf_SYS0300DTO01/Svc_SC_DeleteResponse")>  _
        Function Svc_SC_DeleteAsync(ByVal poEntity As SYS0300SvcRef.SYS0300DTO01) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISYS0300Svc/getList", ReplyAction:="http://tempuri.org/ISYS0300Svc/getListResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SC_Common.SC_ServiceExceptions), Action:="http://tempuri.org/ISYS0300Svc/getListSC_ServiceExceptionsFault", Name:="SC_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_Common"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SYS0300SvcRef.SC_DTOBase)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SYS0300SvcRef.eCRUDMode)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SYS0300SvcRef.SYS0300DTO01)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of SYS0300SvcRef.SYS0300DTO02))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SYS0300SvcRef.SYS0300DTO02)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of SYS0300SvcRef.LKM_SysModuleDTO))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SYS0300SvcRef.LKM_SysModuleDTO)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of SYS0300SvcRef.LKM_SysAppGroupDTO))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SYS0300SvcRef.LKM_SysAppGroupDTO)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of SYS0300SvcRef.LKM_SysAppTypeDTO))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SYS0300SvcRef.LKM_SysAppTypeDTO)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of Object))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SC_Common.SC_ServiceExceptions)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of SC_Common.SC_Error))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SC_Common.SC_Error)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(System.Collections.Generic.List(Of SC_Common.SC_ErrorDetail))),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(SC_Common.SC_ErrorDetail))>  _
        Function getList(ByVal poparam As System.Collections.Generic.List(Of Object)) As System.Collections.Generic.List(Of SYS0300SvcRef.SYS0300DTO02)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISYS0300Svc/getList", ReplyAction:="http://tempuri.org/ISYS0300Svc/getListResponse")>  _
        Function getListAsync(ByVal poparam As System.Collections.Generic.List(Of Object)) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of SYS0300SvcRef.SYS0300DTO02))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISYS0300Svc/getModule", ReplyAction:="http://tempuri.org/ISYS0300Svc/getModuleResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SC_Common.SC_ServiceExceptions), Action:="http://tempuri.org/ISYS0300Svc/getModuleSC_ServiceExceptionsFault", Name:="SC_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_Common")>  _
        Function getModule() As System.Collections.Generic.List(Of SYS0300SvcRef.LKM_SysModuleDTO)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISYS0300Svc/getModule", ReplyAction:="http://tempuri.org/ISYS0300Svc/getModuleResponse")>  _
        Function getModuleAsync() As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of SYS0300SvcRef.LKM_SysModuleDTO))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISYS0300Svc/getAppGroup", ReplyAction:="http://tempuri.org/ISYS0300Svc/getAppGroupResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SC_Common.SC_ServiceExceptions), Action:="http://tempuri.org/ISYS0300Svc/getAppGroupSC_ServiceExceptionsFault", Name:="SC_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_Common")>  _
        Function getAppGroup() As System.Collections.Generic.List(Of SYS0300SvcRef.LKM_SysAppGroupDTO)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISYS0300Svc/getAppGroup", ReplyAction:="http://tempuri.org/ISYS0300Svc/getAppGroupResponse")>  _
        Function getAppGroupAsync() As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of SYS0300SvcRef.LKM_SysAppGroupDTO))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISYS0300Svc/getAppType", ReplyAction:="http://tempuri.org/ISYS0300Svc/getAppTypeResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SC_Common.SC_ServiceExceptions), Action:="http://tempuri.org/ISYS0300Svc/getAppTypeSC_ServiceExceptionsFault", Name:="SC_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/SC_Common")>  _
        Function getAppType() As System.Collections.Generic.List(Of SYS0300SvcRef.LKM_SysAppTypeDTO)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISYS0300Svc/getAppType", ReplyAction:="http://tempuri.org/ISYS0300Svc/getAppTypeResponse")>  _
        Function getAppTypeAsync() As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of SYS0300SvcRef.LKM_SysAppTypeDTO))
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ISYS0300SvcChannel
        Inherits SYS0300SvcRef.ISYS0300Svc, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SYS0300SvcClient
        Inherits System.ServiceModel.ClientBase(Of SYS0300SvcRef.ISYS0300Svc)
        Implements SYS0300SvcRef.ISYS0300Svc
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Svc_SC_GetRecord(ByVal poEntity As SYS0300SvcRef.SYS0300DTO01, ByVal poCRUDMode As SYS0300SvcRef.eCRUDMode) As SYS0300SvcRef.SYS0300DTO01 Implements SYS0300SvcRef.ISYS0300Svc.Svc_SC_GetRecord
            Return MyBase.Channel.Svc_SC_GetRecord(poEntity, poCRUDMode)
        End Function
        
        Public Function Svc_SC_GetRecordAsync(ByVal poEntity As SYS0300SvcRef.SYS0300DTO01, ByVal poCRUDMode As SYS0300SvcRef.eCRUDMode) As System.Threading.Tasks.Task(Of SYS0300SvcRef.SYS0300DTO01) Implements SYS0300SvcRef.ISYS0300Svc.Svc_SC_GetRecordAsync
            Return MyBase.Channel.Svc_SC_GetRecordAsync(poEntity, poCRUDMode)
        End Function
        
        Public Function Svc_SC_Save(ByVal poEntity As SYS0300SvcRef.SYS0300DTO01, ByVal poCRUDMode As SYS0300SvcRef.eCRUDMode) As SYS0300SvcRef.SYS0300DTO01 Implements SYS0300SvcRef.ISYS0300Svc.Svc_SC_Save
            Return MyBase.Channel.Svc_SC_Save(poEntity, poCRUDMode)
        End Function
        
        Public Function Svc_SC_SaveAsync(ByVal poEntity As SYS0300SvcRef.SYS0300DTO01, ByVal poCRUDMode As SYS0300SvcRef.eCRUDMode) As System.Threading.Tasks.Task(Of SYS0300SvcRef.SYS0300DTO01) Implements SYS0300SvcRef.ISYS0300Svc.Svc_SC_SaveAsync
            Return MyBase.Channel.Svc_SC_SaveAsync(poEntity, poCRUDMode)
        End Function
        
        Public Sub Svc_SC_Delete(ByVal poEntity As SYS0300SvcRef.SYS0300DTO01) Implements SYS0300SvcRef.ISYS0300Svc.Svc_SC_Delete
            MyBase.Channel.Svc_SC_Delete(poEntity)
        End Sub
        
        Public Function Svc_SC_DeleteAsync(ByVal poEntity As SYS0300SvcRef.SYS0300DTO01) As System.Threading.Tasks.Task Implements SYS0300SvcRef.ISYS0300Svc.Svc_SC_DeleteAsync
            Return MyBase.Channel.Svc_SC_DeleteAsync(poEntity)
        End Function
        
        Public Function getList(ByVal poparam As System.Collections.Generic.List(Of Object)) As System.Collections.Generic.List(Of SYS0300SvcRef.SYS0300DTO02) Implements SYS0300SvcRef.ISYS0300Svc.getList
            Return MyBase.Channel.getList(poparam)
        End Function
        
        Public Function getListAsync(ByVal poparam As System.Collections.Generic.List(Of Object)) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of SYS0300SvcRef.SYS0300DTO02)) Implements SYS0300SvcRef.ISYS0300Svc.getListAsync
            Return MyBase.Channel.getListAsync(poparam)
        End Function
        
        Public Function getModule() As System.Collections.Generic.List(Of SYS0300SvcRef.LKM_SysModuleDTO) Implements SYS0300SvcRef.ISYS0300Svc.getModule
            Return MyBase.Channel.getModule
        End Function
        
        Public Function getModuleAsync() As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of SYS0300SvcRef.LKM_SysModuleDTO)) Implements SYS0300SvcRef.ISYS0300Svc.getModuleAsync
            Return MyBase.Channel.getModuleAsync
        End Function
        
        Public Function getAppGroup() As System.Collections.Generic.List(Of SYS0300SvcRef.LKM_SysAppGroupDTO) Implements SYS0300SvcRef.ISYS0300Svc.getAppGroup
            Return MyBase.Channel.getAppGroup
        End Function
        
        Public Function getAppGroupAsync() As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of SYS0300SvcRef.LKM_SysAppGroupDTO)) Implements SYS0300SvcRef.ISYS0300Svc.getAppGroupAsync
            Return MyBase.Channel.getAppGroupAsync
        End Function
        
        Public Function getAppType() As System.Collections.Generic.List(Of SYS0300SvcRef.LKM_SysAppTypeDTO) Implements SYS0300SvcRef.ISYS0300Svc.getAppType
            Return MyBase.Channel.getAppType
        End Function
        
        Public Function getAppTypeAsync() As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of SYS0300SvcRef.LKM_SysAppTypeDTO)) Implements SYS0300SvcRef.ISYS0300Svc.getAppTypeAsync
            Return MyBase.Channel.getAppTypeAsync
        End Function
    End Class
End Namespace
